### ISSUE TITLE
"config" file does not exist when creating cluster

### ISSUE THREAD

**Issue by rot26** [kubernetes/kops#533] opened 2016-09-28 20:51 UTC
Hi @justinsb et al.  I am following your request to submit an issue.

When I create a cluster following the README.md instructions, I get the following error:

Create Cluster

``` sh
${GOPATH}/bin/kops create cluster --cloud=aws --zones=us-west-2a --v=8 ${NAME}
```

STDOUT

``` sh
I0928 13:29:16.460940   98891 context.go:140] Found bucket "minerva-kops-state-store" in region "us-west-2"
I0928 13:29:16.461045   98891 s3fs.go:125] Reading file "s3://minerva-kops-state-store/dev.k8s.minervalab.com/config"
I0928 13:29:16.713912   98891 cluster.go:419] Computed CIDR for subnet in zone "us-west-2a" as "172.20.xxx.xxx/19"
I0928 13:29:16.713940   98891 cluster.go:362] Assigned CIDR 172.20.xxx.xxx/19 to zone us-west-2a
I0928 13:29:16.943752   98891 cluster.go:338] Using kubernetes latest stable version: v1.4.0
I0928 13:29:16.944479   98891 populate_cluster_spec.go:270] Defaulted KubeControllerManager.ClusterCIDR to 100.96.xxx.xxx/11
I0928 13:29:16.944496   98891 populate_cluster_spec.go:277] Defaulted ServiceClusterIPRange to 100.64.0.0/13
W0928 13:29:16.944558   98891 populate_cluster_spec.go:182] Normalizing kubernetes version: "v1.4.0" -> "1.4.0"
I0928 13:29:16.944589   98891 aws_utils.go:21] Querying EC2 for all valid regions
I0928 13:29:17.319107   98891 aws_cloud.go:502] Querying EC2 for all valid zones in region "us-west-2"
I0928 13:29:17.608141   98891 aws_cloud.go:559] Querying for all route53 zones to find match for "dev.k8s.minervalab.com"
I0928 13:29:18.061364   98891 populate_cluster_spec.go:196] Defaulting DNS zone to: Z1XXXXXXXXXWV6

error building complete spec: error reading directory "config": file does not exist
```

Error:

``` sh
error building complete spec: error reading directory "config": file does not exist
```

Versions:

``` sh
kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7+a2cba278", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"not a git tree", BuildDate:"2016-09-23T01:55:57Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
```

``` sh
${GOPATH}/bin/kops version
Version git-6388a77
```

**Comment by rot26** [comment] 2016-09-28 22:07
Wow.  So the root issue for me ended up being that I had my GOPATH set to 

```
~/.go
```
(notice the "." prefix)
instead of

```
~/go
```

**Comment by justinsb** [comment] 2016-09-29 04:32
I'm glad we found the root cause!  I'm going to leave this open while I fix it though - I don't think it will affect many people, but the regex is overly broad.

**Comment by stevezau** [comment] 2016-10-03 08:33
I'm also getting this on the latest version but changing go path to ~/go does not fix it

**Comment by opennomad** [comment] 2016-10-05 17:36
@stevezau I had to re-run the `make` for kops after relocating to new location. Then it worked

**Comment by justinsb** [comment] 2016-12-28 19:54
Pretty sure this is fixed now - we tightened up the ignores to be e.g. `-ignore="\\.DS_Store" -ignore="bindata\\.go" -ignore="vfs\\.go"`

**Closed by justinsb** 2016-12-28 19:54 UTC
