### ISSUE TITLE
CNI+Weave networking and pods stuck in ContainerCreating and Terminating

### ISSUE THREAD

**Issue by caarlos0** [kubernetes/kops#2346] opened 2017-04-11 23:15 UTC
So, I had a cluster, created with `kops 1.5.0-alpha4` and running `kubernetes 1.5.3`. 
The cluster was created with CNI networking and then weave was setup with `kubectl apply -f https://git.io/weave-kube`.
It also has private topology and all that. It runs on AWS.

Everything was working as expected for ~2 months.

Then, I decided to upgrade to `kubernetes 1.5.6`, so I grabbed `kops 1.5.3`, and did:

```sh
$ kops edit cluster $NAME
# changed kubernetes version from 1.5.2 to 1.5.6
$ kops update cluster $NAME --yes
$ kops rolling-update cluster --yes
```

And it was still ok for a few days.

Then we also decided to change the nodes from `t2.large` to `r3.large` spot instances. It worked for a day, and then I saw that kube-dns-* pods were forever on `ContainerCreateing`, and its failing due to `cni config uninitialized; skipping pod`.

I tried to force a restart of the pods with `kubectl delete pod`, but it only made it worse:

```
kubectl get pods -n kube-system | grep -vi running
NAME                                                    READY     STATUS              RESTARTS   AGE
heapster-564189836-nt32b                                0/1       ContainerCreating   0          1h
kube-dns-782804071-5l26z                                0/4       ContainerCreating   0          3m
kube-dns-782804071-xwh1z                                0/4       Terminating         0          1h
kube-dns-autoscaler-2813114833-1hg98                    0/1       ContainerCreating   0          3m
kube-dns-autoscaler-2813114833-mgxb9                    0/1       Terminating         0          1h
kubernetes-dashboard-3203831700-q14pd                   0/1       ContainerCreating   0          35m
monitoring-influxdb-grafana-v4-q2vx8                    0/2       ContainerCreating   0          1h
```

I also tried to sequentially `kubectl delete pod weave-xyz`. The weave pods wen't up but the others were still failing.

@justinsb asked me on slack to check which weave version I was running, and it was `1.9.4` (I suspect someone upgrade it but no one confess 🤷‍♂️ ). 

I also checked that some time, pods were scheduled but would keep in that state forever, without any errors (`Successfully assigned hello-2533203682-94wg9 to ip-172-16-62-80.ec2.internal`) instead of the previous CNI error.

The nodes were all ok according to `kubectl describe node`:

```
Conditions:
 Type            Status    LastHeartbeatTime            LastTransitionTime            Reason                Message
 ----            ------    -----------------            ------------------            ------                -------
 OutOfDisk         False     Tue, 11 Apr 2017 18:30:46 -0300     Tue, 11 Apr 2017 17:35:14 -0300     KubeletHasSufficientDisk     kubelet has sufficient disk space available
 MemoryPressure     False     Tue, 11 Apr 2017 18:30:46 -0300     Tue, 11 Apr 2017 17:35:14 -0300     KubeletHasSufficientMemory     kubelet has sufficient memory available
 DiskPressure         False     Tue, 11 Apr 2017 18:30:46 -0300     Tue, 11 Apr 2017 17:35:14 -0300     KubeletHasNoDiskPressure     kubelet has no disk pressure
 Ready         True     Tue, 11 Apr 2017 18:30:46 -0300     Tue, 11 Apr 2017 17:35:24 -0300     KubeletReady             kubelet is posting ready status
```

`docker ps` on the node were a pod were scheduled, would show that half of the pod is there:

```
3f2f30271982        gcr.io/google_containers/pause-amd64:3.0     "/pause"                 42 minutes ago      Up 42 minutes                           k8s_POD.d8dbe16c_kube-dns-782804071-5k5tz_kube-system_97a905c5-1ef8-11e7-a4f8-0a75bdb13dae_db12b739
```

`docker logs` of weave containers didn't contain anything weird, all looks normal.

Finally, looking into `journalctl -u kubelet`, we found this:

```
NetworkPlugin cni failed on the status hook for pod 'kube-dns-782804071-5k5tz' - Unexpected command output Device "eth0" does not exist.
```

However, `ifconfig` shows `eth0`...

@justinsb launched a cluster with the same versions and this bug didn't happened.

After some time trying to figure it out, we finally manage to fix it:

```
kubectl delete DaemonSet/weave-net -n kube-system
```

And `kops edit cluster $NAME`, changing the networking from CNI to weave directly.

Then, `kops update cluster $NAME`, relevant parts of the output showing:

```
  ManagedFile/dev.contaazul.local-addons-bootstrap
  	Contents
  	                    	...
  	                    	        k8s-addon: storage-aws.addons.k8s.io
  	                    	      version: 1.5.0
  	                    	+   - manifest: networking.weave/v1.9.3.yaml
  	                    	+     name: networking.weave
  	                    	+     selector:
  	                    	+       role.kubernetes.io/networking: "1"
  	                    	+     version: 1.9.3
```

Then, `kops update cluster dev.contaazul.local --yes`, which says

```
Cluster changes have been applied to the cloud.

Changes may require instances to restart: kops rolling-update cluster
```

But then, `kops rolling-update cluster --yes` shows

```
Using cluster from kubectl context: $CTX

NAME			STATUS	NEEDUPDATE	READY	MIN	MAX	NODES
master-us-east-1a	Ready	0		1	1	1	1
nodes			Ready	0		3	1	6	3

No rolling-update required.
```

Either way, it came back to life.

- I don't understand why it stoped working, that's why I put all information I thought could be relevant.
- The `rolling-update` in the last part may be a bug... ?

If you guys need more info or help with anything, let me know please (also feel free to change the title to something maybe more relevant - I really didn't know how to name it).

Oh, thanks again @justinsb for helping me fix this 🍻

**Comment by steventranjs** [comment] 2017-04-19 00:48
I encountered this problem too.

**Comment by chrislovecnm** [comment] 2017-04-23 19:45
Can anyone shed some light to a root cause?

**Comment by ahawkins** [comment] 2017-04-25 10:55
I'm having the same issue, but not caused in the same way. I'm not sure if this is a kops things or a Kubernetes things. We're having the same issue (pods stuck in `ContainerCreating` or anything else) _and_ the `docker ps` only showing the pause container (`gcr.io/google_containers/pause-amd64:3.0`). However we are having this problem without upgrading the version or anything else.

Here's some relevant info from our cluster spec

```
  kubernetesVersion: 1.5.2
  networkCIDR: 172.20.0.0/16
  networking:
    weave: {}
```

Our cluster with created with `--networking=weave`. My "solution" to this problem is to terminate nodes. This seems to fix the problem but it comes back after some time.

**Comment by Miyurz** [comment] 2017-04-25 11:05
Looks related to this https://github.com/weaveworks/weave/issues/2797

@chrislovecnm ^

**Comment by while1eq1** [comment] 2017-04-25 12:02
This is primarily due to the scheduler attempting to bring up the pods before the CNI is up, I had this issue with the flannel network as well.

**Comment by while1eq1** [comment] 2017-04-25 12:04
I know this is another project entirely though I'm pretty confident it's related https://github.com/kubernetes-incubator/kube-aws/issues/495

**Comment by chrislovecnm** [comment] 2017-04-26 02:31
We need to bump the flannel version.

**Comment by while1eq1** [comment] 2017-04-26 02:33
Fine with me, I know the newer versions of all the CNIs addressed this I
believe

**Comment by chrislovecnm** [comment] 2017-04-26 04:39
@while1eq1 so k8s 1.6.2 is working with flannel?  This is closing a blocker item for release ... want to make sure we are good to go

**Comment by ahawkins** [comment] 2017-04-26 05:57
I restarted weave pods (by deleting pods for the existing DaemonSet) and seems pods are starting again.

**Comment by while1eq1** [comment] 2017-04-26 06:07
k8s 1.6.2 is working just fine with flannel 0.7.0  (after compiling kops
with your PR updating the CNI package, not before)

I've done extensive testing and containers are no long getting stuck in
"ContainerCreating"

Containers

**Comment by Miyurz** [comment] 2017-04-26 06:41
@while1eq1 have you tested this with weave too ? We (I and @ahawkins ) have been using weave as a part of kops provisioning though we wanted to try other network managers but never had the time to do so.

**Comment by while1eq1** [comment] 2017-04-26 22:16
I have not tested with weave.

**Comment by andreychernih** [comment] 2017-05-12 04:07
I just had the same problem with new cluster running with Kubernetes 1.6.2 and kops 
1.6.0-beta.1. I am using calico as CNI plugin. The affected containers were `kube-dns`, `kube-dns-autscaler` and `tiller` (I install helm right after cluster comes up). They all stuck in `ContainerCreating` state.

```
[root@b99841a5f040 kops]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                                                READY     STATUS              RESTARTS   AGE
kube-system   calico-node-gq9hp                                                   2/2       Running             0          1m
kube-system   calico-node-k6zz1                                                   2/2       Running             0          2m
kube-system   calico-node-q230m                                                   2/2       Running             0          1m
kube-system   calico-policy-controller-811246363-bs2sj                            1/1       Running             0          2m
kube-system   dns-controller-3576371413-w42wn                                     1/1       Running             0          2m
kube-system   etcd-server-events-ip-10-52-63-53.us-west-2.compute.internal        1/1       Running             0          2m
kube-system   etcd-server-ip-10-52-63-53.us-west-2.compute.internal               1/1       Running             0          2m
kube-system   kube-apiserver-ip-10-52-63-53.us-west-2.compute.internal            1/1       Running             0          2m
kube-system   kube-controller-manager-ip-10-52-63-53.us-west-2.compute.internal   1/1       Running             0          3m
kube-system   kube-dns-1321724180-j5snh                                           0/3       ContainerCreating   0          2m
kube-system   kube-dns-autoscaler-265231812-jp8v4                                 0/1       ContainerCreating   0          2m
kube-system   kube-proxy-ip-10-52-56-62.us-west-2.compute.internal                1/1       Running             0          1m
kube-system   kube-proxy-ip-10-52-63-53.us-west-2.compute.internal                1/1       Running             0          3m
kube-system   kube-scheduler-ip-10-52-63-53.us-west-2.compute.internal            1/1       Running             0          2m
kube-system   tiller-deploy-1172528075-15mlp                                      0/1       ContainerCreating   0          2m
```

```
Name:           tiller-deploy-1172528075-15mlp
Namespace:      kube-system
Node:           ip-10-52-56-62.us-west-2.compute.internal/10.52.56.62
Start Time:     Fri, 12 May 2017 03:53:02 +0000
Labels:         app=helm
                name=tiller
                pod-template-hash=1172528075
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-1172528075","uid":"35c88fbe-36c6-11e
7-a079-06f...
Status:         Pending
IP:
Controllers:    ReplicaSet/tiller-deploy-1172528075
Containers:
  tiller:
    Container ID:
    Image:              gcr.io/kubernetes-helm/tiller:v2.3.0
    Image ID:
    Port:               44134/TCP
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:          http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE: kube-system
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-3dnxn (ro)
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  default-token-3dnxn:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-3dnxn
    Optional:   false
QoS Class:      BestEffort
Node-Selectors: <none>
Tolerations:    node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
                node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen     LastSeen        Count   From                                                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                                                    -------------   --------        ------                  -------
  4m            4m              6       default-scheduler                                                       Warning         FailedScheduling        no nodes available to schedule pods
  4m            3m              3       default-scheduler                                                       Warning         FailedScheduling        No nodes are available that match all of the following
 predicates:: PodToleratesNodeTaints (1).
  2m            2m              1       default-scheduler                                                       Normal          Scheduled               Successfully assigned tiller-deploy-1172528075-15mlp t
o ip-10-52-56-62.us-west-2.compute.internal
  1m            1m              1       kubelet, ip-10-52-56-62.us-west-2.compute.internal                      Warning         FailedSync              Error syncing pod, skipping: failed to "KillPodSandbox
" for "35c9651e-36c6-11e7-a079-06f36b8a8f4e" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"_\" network: CNI failed to retrieve network namespace path: Erro
r: No such container: 5be57f525a2fe2283f482fe5877a8c1b5912a2e1209cce10d08f06a2e26f6d0a"

  18s   18s     1       kubelet, ip-10-52-56-62.us-west-2.compute.internal              Warning FailedSync      Error syncing pod, skipping: failed to "KillPodSandbox" for "35c9651e-36c6-11e7-a079-06f36b8a8
f4e" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"_\" network: CNI failed to retrieve network namespace path: Error: No such container: f178c4e511606c2ae8
6ee14f5e5cb326a17136aa87bcc2044d27a3cdd5fb3d2c"

  17s   17s     1       kubelet, ip-10-52-56-62.us-west-2.compute.internal              Warning FailedSync      Error syncing pod, skipping: rpc error: code = 2 desc = Error: No such container: e2d8babeb8bc
99167a560a4fd006f2573d1fe311cd1ab20c8616dff714675c7a
  2m    1s      38      kubelet, ip-10-52-56-62.us-west-2.compute.internal              Warning FailedSync      Error syncing pod, skipping: failed to "CreatePodSandbox" for "tiller-deploy-1172528075-15mlp_
kube-system(35c9651e-36c6-11e7-a079-06f36b8a8f4e)" with CreatePodSandboxError: "CreatePodSandbox for pod \"tiller-deploy-1172528075-15mlp_kube-system(35c9651e-36c6-11e7-a079-06f36b8a8f4e)\" failed: rpc erro
r: code = 2 desc = NetworkPlugin cni failed to set up pod \"tiller-deploy-1172528075-15mlp_kube-system\" network: No configured Calico pools"

  2m    0s      40      kubelet, ip-10-52-56-62.us-west-2.compute.internal              Normal  SandboxChanged  Pod sandbox changed, it will be killed and re-created.
```

Lots of errors like this on one on nodes:

```
May 12 04:05:16 ip-10-52-44-104 kubelet[2572]: W0512 04:05:16.808129    2572 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "tiller-deploy-1172528075-2xvn8_kube-system": Unexpected command output nsenter: cannot open : No such file or directory
May 12 04:05:16 ip-10-52-44-104 kubelet[2572]: with error: exit status 1
May 12 04:05:16 ip-10-52-44-104 kubelet[2572]: W0512 04:05:16.815469    2572 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "tiller-deploy-1172528075-2xvn8_kube-system": Unexpected command output nsenter: cannot open : No such file or directory
May 12 04:05:16 ip-10-52-44-104 kubelet[2572]: with error: exit status 1
May 12 04:05:16 ip-10-52-44-104 kubelet[2572]: W0512 04:05:16.824879    2572 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "tiller-deploy-1172528075-2xvn8_kube-system": Unexpected command output nsenter: cannot open : No such file or directory
May 12 04:05:16 ip-10-52-44-104 kubelet[2572]: with error: exit status 1
```

**Comment by andreychernih** [comment] 2017-05-12 20:23
Also:

```
May 12 20:22:37 ip-10-52-57-51 kubelet[2644]: E0512 20:22:37.423255    2644 remote_runtime.go:86] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "kube-dns-1321724180-x1hxd_kube-system" network: No configured Calico pools
```

**Comment by andreychernih** [comment] 2017-05-12 20:57
[Calico 2.1.5](http://docs.projectcalico.org/v2.1/releases/) fixes this issue, I've verified by manually bumping versions in `addons/networking.projectcalico.org/k8s-1.6.yaml`. Calico has been updated to 2.1.5 in master already, so just need to wait for new release.

**Comment by chrislovecnm** [comment] 2017-05-12 22:00
Since this is fixed in master, I will close

**Closed by chrislovecnm** 2017-05-12 22:00 UTC
