### ISSUE TITLE
Kops e2e flakes

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#1041] opened 2016-12-03 20:01 UTC
e2e is currently borked.

```
W1202 13:20:43.899] W1202 13:20:43.898817     563 executor.go:108] error running task "vpc/aws-kops-agent-pr-67-0.test-aws.k8s.io" (9m55.81536669s remaining to succeed): error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
```

@zmerlynn can you request that the vpc limits in the account are increased?  Let me know if I should have opened this issue in the test project.

**Comment by justinsb** [comment] 2016-12-03 23:37
I think I am also seeing a lot of Rate Limit errors.  I added logging of that in #1046 so it would be more obvious, but that isn't going to address root cause.  I suspect that we leak objects when we can't talk to the API.

I had a look and I don't see any egregiously bad API requests (though I could be missing something).

We hit the same thing in kubernetes/kubernetes, and two things learned there:

1) The aws-sdk-go does per-request back-off, but we actually want to back-off everyone when we are rate limited.  (It isn't entirely clear, but I think that rate limited requests count against the rate limits).  We have a global heuristic delayer that can actually throttle all requests based on observed rate limits; we could pull this across.  But...

2) It's also possible that it isn't kops at all, but something else in the cluster.  For example, we know that the new volume code in k8s calls DescribeVolumes more aggressively.  Or it could be Jenkins running against AWS (?).  Or anything really....


For (2), can we turn logging of all AWS requests using CloudTrail @zmerlynn , and see if we can get a feel for which requests are happening?  We could also systematize this in future if it proves valuable (e.g. track API calls in e2e).  But we can start with just manually checking the logs and figuring out whether the problem is something misbehaving vs sheer weight of PRs being built, and knowing the problematic call should provide a pretty big hint...

**Comment by chrislovecnm** [comment] 2016-12-03 23:53
I am see that we are also hitting quota limits. I would recommend increasing those, for instance VPC.  Also, I am wondering if we are cleaning house properly or are we leaving unused resources around.

Ping me if u need to lookup the spreadsheet that shows are limits.

**Comment by chrislovecnm** [comment] 2016-12-04 01:31
We are hitting API limits for sure. 

From latest build:
1203 16:10:27.372] error querying for valid AZs in "us-west-2" - verify your AWS credentials.  Error: RequestLimitExceeded: Request limit exceeded.

**Comment by zmerlynn** [comment] 2016-12-05 17:50
@justinsb: I actually have CloudTrail enabled already on that account, and one of my priorities was working on leak detection via CloudTrail (but it looks like a bit of a pain).

**Comment by justinsb** [comment] 2016-12-05 18:30
@zml: awesome.  Any chance you could get me the cloudtrail logs or generate some report so we can see what requests we are making?

**Comment by kris-nova** [comment] 2016-12-11 19:05
We were able to get `e2e` stable-er and are now focusing on getting `e2e` stable-er-er

Closing this to keep up with it @chrislovecnm @justinsb @zmerlynn - cool?

**Closed by kris-nova** 2016-12-11 19:05 UTC
Labels: P0
