### ISSUE TITLE
Root EBS volumes do not get tagged

### ISSUE THREAD

**Issue by schollii** [kubernetes/kops#8785] opened 2020-03-23 15:39 UTC
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
 
Version 1.13.0 (git-be5fb9019)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Edited the kops_cluster.yaml to have cloudLabels. 
Ran kops update --target terraform and kops rolling-update

**5. What happened after the commands executed?**

Terraform showed that the autoscaling groups and the etcd ebs volumes would get the new tags from cloudLabels. This was confirmed after terraform apply. However the other ebs volumes (ie the root ones) did not. Not on master nodes, nor on worker nodes. 

**6. What did you expect to happen?**

All volumes associated with all the nodes created would have the cloudLabels as tags. Although the https://github.com/kubernetes/kops/blob/master/docs/labels.md#cloudlabels is not clear, led me to think at least the master node ebs root volumes would have the tags. 

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

I will add this if really needed. I have a feeling this is just not supported by kops, or perhaps this got fixed later. Either way the docs should be fixed to clarify which volumes get the tags eg kops <= 1.13 only etcd volumes get them and the rest has to be done through AWS CLI or SDK; for kops > 1.13 all volumes get them. And indicate whether recommended to use aws CLI from an "additional user data script" that can be specified in the yaml file.  

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

I will add this if really needed. 

**9. Anything else do we need to know?**

**Comment by johngmyers** [comment] 2020-03-24 04:06
Duplicate of #3358
/close

**Closed** 2020-03-24 04:06 UTC
