### ISSUE TITLE
Incorrect ssh bastion host information

### ISSUE THREAD

**Issue by aledbf** [kubernetes/kops#1489] opened 2017-01-16 02:43 UTC
kops version 1.5.0-alpha3
cluster created with flags `--bastion --topology private`

At the end showed:
```
Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * list nodes: kubectl get nodes --show-labels
 * ssh to the bastion: ssh -i ~/.ssh/id_rsa admin@api.xxxxxxx
```

but it should be 

```
* ssh to the bastion: ssh -i ~/.ssh/id_rsa admin@bastion.xxxxxxx
```

**Comment by kris-nova** [comment] 2017-01-16 03:10
Dupe of #1207 

Fixing in https://github.com/kubernetes/kops/pull/1253

I hadn't touched that PR in a while - will take a crack at it tonight.

@aledbf closing this as a duplicate, but feel free to re-open if I missed something.

**Comment by yissachar** [comment] 2017-01-16 21:05
@kris-nova I'm not sure it's the same issue, even though it's the same line.

#1207 is about the wrong SSH key being printed (which your PR will hopefully address), while this one is about the wrong server name being printed (`api` vs `bastion`).

I believe that [line 227](https://github.com/kubernetes/kops/blob/f70029cae0d99cc714769ccc8dbf746329d3fa3c/cmd/kops/update_cluster.go#L227) should use `cluster.Spec.Topology.Bastion.BastionPublicName` instead, but I haven't tested this.

**Comment by kris-nova** [comment] 2017-01-17 18:49
Reopenning thanks @yissachar

**Closed** 2017-01-25 05:59 UTC
