### ISSUE TITLE
kops cluster in existing vpc and subnets not working

### ISSUE THREAD

**Issue by kaspernissen** [kubernetes/kops#1600] opened 2017-01-24 13:04 UTC
**Kops version**: Version 1.5.0-alpha4 (git-b336083)
I'm trying to setup a kops cluster in an existing VPC with existing subnets.

**Steps**
1. Creating cluster with the following configuration
```bash
kops create cluster \
    --node-count 3 \
    --zones eu-west-1a,eu-west-1b,eu-west-1c \
    --master-zones eu-west-1a,eu-west-1b,eu-west-1c \
    --dns-zone staging.example.com \
    --node-size t2.medium \
    --master-size t2.medium \
    --topology private \
    --networking weave \
    --name=${CLUSTER_NAME} \
    --vpc=${VPC_ID} \
    --bastion \
    ${NAME}
```

2. Edit cluster configuration for the subnets as follows:

```
 - id: subnet-380e4861
    name: eu-west-1a
    type: Private
    zone: eu-west-1a
  - id: subnet-926e68f7
    name: eu-west-1b
    type: Private
    zone: eu-west-1b
  - id: subnet-161c2d60
    name: eu-west-1c
    type: Private
    zone: eu-west-1c
  - id: subnet-390e4860
    name: utility-eu-west-1a
    type: Utility
    zone: eu-west-1a
  - id: subnet-2f5e634b
    name: utility-eu-west-1b
    type: Utility
    zone: eu-west-1b
  - id: subnet-541c2d22
    name: utility-eu-west-1c
    type: Utility
    zone: eu-west-1c
```

3. then I've ran `kops update cluster .... --yes`

After 30 minutes I cannot access the cluster using `kubectl`.

I've noticed some wierd entries in Route53
![route53-settings](https://cloud.githubusercontent.com/assets/4429108/22248139/7d62848e-e23d-11e6-9a44-00b249685ce7.png)

Tried changing the dns entries without any luck. I noticed that the TTL is different than the other entries as well. It's set to 10.

**Error**
`kubectl`outputs the following:

```
$ kubectl get pods
Unable to connect to the server: EOF
```

The kubernetes api-loadbalancer is not registering any healthy nodes and outputs
```
Status: 0 of 3 instances in service
```

**Comment by yissachar** [comment] 2017-01-24 16:21
Dupe of https://github.com/kubernetes/kops/issues/1220

**Comment by justinsb** [comment] 2017-01-26 16:06
Going to close as a dup if that's OK, as I believe we're discussing over in #1220.  If not OK, just comment/reopen.

**Closed by justinsb** 2017-01-26 16:06 UTC
