### ISSUE TITLE
AWS ENA Driver Not Enabled On Default AMI

### ISSUE THREAD

**Issue by tcf909** [kubernetes/kops#1558] opened 2017-01-20 02:15 UTC
Hello,

I noticed that the ENA (Enhanced Networking Adapter) isn't enabled by default in the AMIs (1.4) that kops uses by default:

```
root@ip-172-21-35-87:~# cat /etc/debian_version
8.6
root@ip-172-21-35-87:~# ethtool -i eth0
driver: vif
```
```
$ kops version
Version 1.5.0-alpha3 (git-51b7644)
```
AMI Version: k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-12-05 (ami-03fdf814)

References:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html
https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie

**Comment by justinsb** [comment] 2017-01-20 02:34
Which instance size was this on?  Did it have enhanced networking available?

**Comment by tcf909** [comment] 2017-01-20 03:12
It was an R4.xlarge. Should be available.

</reply on the go>

**Comment by justinsb** [comment] 2017-01-20 04:41
I see now - this is a separate driver from the ixgbevf driver - my mistake.

We'll have to add a module to the base image:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html

**Comment by justinsb** [comment] 2017-01-20 04:54
It's not entirely relevant, but I confirmed that the ixgbevf driver is installed and enabled on e.g. a c4.large:

```
> ethtool -i eth0
driver: ixgbevf
version: 2.12.1-k
firmware-version: 
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

**Comment by tcf909** [comment] 2017-01-20 05:06
Awesome. Definitely good to know. I wonder what the real difference is
between the ENA and the intel one. Anyway, really appreciate your efforts.

**Comment by zytek** [comment] 2017-01-31 20:55
AWS recommends ixgbevf > 2.14 for stability and performance.
ENA driver is needed on those beefy 20Gbit/s instances. This driver is not available on stock Ubuntu images and has to be installed manually.

Does kops/kubernetes provide any 'official' AMIs ? always thought that it utilises 'bare' images. 

edit: ok, I see we do, so I guess this should be added (bumped ixgbevf and ENA driver)

**Comment by ottoyiu** [comment] 2017-02-03 00:26
Does anyone know if the ixgbevf 2.12.1-k in Debian 8.6 `k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09 (ami-aaf84aca)` is affected by the stability issues, of TCP timeouts and just random packet corruption?

I'm getting many of these as well:
```
[22117.455919] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[22117.489707] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready

```

**Comment by justinsb** [comment] 2017-02-03 04:40
On ixgbevf:

On the "k8s AMIs" (which are debian jessie with a 4.4. kernel), we're running the ixgbevf driver from the linux kernel, not the out of tree version.  The versioning numbering appears to not correspond directly.  We switched to this as part of the move to the 4.4 kernel; with the jessie kernel we were seeing kernel panics, particularly on m4 instances (_with_ the AWS-recommended driver): https://github.com/kubernetes/kubernetes/issues/30706

I compared the 2.12.1 driver from sourceforge with the 2.14.2 driver (I could not find the upstream version control):

*  2.14.2 introduced `ixgbevf_check_tx_hang`, added here: https://github.com/torvalds/linux/commit/e08400b707739f0eca1645413924743466ea70b8, and in kernel >= 4.0
* 2.14.2 introduced `ixgbevf_set_ivar`, added in the initial commit of the driver into the kernel https://github.com/torvalds/linux/commit/92915f71201b43762fbe05dbfb1a1a0de9c8adb9 .  Note that a version somewhere in between 2.12.1 and 2.14.2 was labeled in the kernel as `1.0.0-k0`.  This suggests that the `-k` scheme is not comparable to the non-k scheme.
* 2.14.2 introduced an errata check, in the kernel in https://github.com/torvalds/linux/commit/8bae1b2b13beb4cf4c0f119f97640503c2b74b0f .

(there are more differences, but these seemed a reasonable sample of non-trivial changes) 

@Jkirsher I see you do a lot of the work on the ixgbevf driver in the kernel...  Is it reasonable to run the ixgbevf driver from the 4.4 LTS kernel on AWS?  Any guidance is greatly appreciated!

**Comment by Jkirsher** [comment] 2017-02-03 06:47
On Thu, 2017-02-02 at 20:40 -0800, Justin Santa Barbara wrote:
> On ixgbevf:
> On the "k8s AMIs" (which are debian jessie with a 4.4. kernel), we're
> running the ixgbevf driver from the linux kernel, not the out of tree
> version. The versioning numbering appears to not correspond directly. We
> switched to this as part of the move to the 4.4 kernel; with the jessie
> kernel we were seeing kernel panics, particularly on m4 instances (with
> the AWS-recommended driver): kubernetes/kubernetes#30706
> I compared the 2.12.1 driver from sourceforge with the 2.14.2 driver (I
> could not find the upstream version control):
> 2.14.2 introduced ixgbevf_check_tx_hang, added here: torvalds/linux@e0840
> 0b, and in kernel >= 4.0
> 2.14.2 introduced ixgbevf_set_ivar, added in the initial commit of the
> driver into the kernel torvalds/linux@92915f7 . Note that a version
> somewhere in between 2.12.1 and 2.14.2 was labeled in the kernel as
> 1.0.0-k0. This suggests that the -k scheme is not comparable to the non-k 
> scheme.
> 2.14.2 introduced an errata check, in the kernel in torvalds/linux@8bae1b
> 2 .
> (there are more differences, but these seemed a reasonable sample of non-
> trivial changes)
> @Jkirsher I see you do a lot of the work on the ixgbevf driver in the
> kernel... Is it reasonable to run the ixgbevf driver from the 4.4 LTS
> kernel on AWS? Any guidance is greatly appreciated!
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Using the in-kernel driver is preferred, unless you are seeing issues.  At
which point, our first suggestion is to try the sourceforge.net driver, to
see if the issue goes away (which would mean we fixed a known issue and
have not pushed the fix upstream yet).   For the most part, the upstream
driver is kept up-to-date on a regular basis, so there should not be a
large discrepancy between the in-kernel and out-of-kernel drivers.

**Comment by justinsb** [comment] 2017-02-05 21:23
Thanks @Jkirsher so much for the guidance on the ixgbevf driver :-)

**Comment by erulabs** [comment] 2017-04-27 03:04
FWIW The `linux-aws` package in Ubuntu 16.04 is a huge performance win for a number of reasons, as well as providing the ENA/ixgbevf drivers out of the box. Other than that package nothing is required save marking the image as "SR-IOV" ready - Perhaps kube should install this when detecting it's installing on Ubuntu on AWS?

**Comment by zapman449** [comment] 2017-05-23 01:34
Another +1 for this.

Running kops 1.5.3, kubernetes 1.5.5 on r4.xlarge shows the `vif` driver in play:

```
# ethtool -i eth0
driver: vif
# cat /etc/debian_version
8.8
```

But I concur that a c4.2xlarge shows:

```
$ sudo ethtool -i eth0
driver: ixgbevf
$ cat /etc/debian_version
8.7
```

(The latter cluster will be updated later this week).

**Comment by jnicholls** [comment] 2017-06-02 12:05
I have an m4.large instance that supports enhanced networking and thus should run the ixgbevf driver.  Can we get kops to set all of this up for us in the k8s debian AMI?  Otherwise I'll probably just move over to Ubuntu 16.04.

**Comment by jmasonISP** [comment] 2017-08-14 23:17
From my limited experience the ENA driver is a must.

I had a gRPC service that was experiencing poor throughput on a Kops created cluster and I narrowed it down to the fact that the default Debian image kops uses did not have the ENA installed. After making my own AMI from the kops default Debian image + ENA I have seen a ~7x improvement in throughput on i3.xlarge nodes (single node throughput increased from 1.2Gbps -> 8.03Gbps).

Cluster Setup:
Node Size: i3.xlarge
Topology: private
Networking: weave

**Comment by bcorijn** [comment] 2017-08-17 13:29
After seeing this mentioned on HN I double-checked my own cluster, and sure enough my R4.XL machines running the `kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28` AMI are not running with ENA enabled. 
```
$ cat /etc/debian_version
8.9
$ sudo modinfo ena
modinfo: ERROR: Module ena not found.
$ sudo ethtool -i eth0
driver: vif
version:
firmware-version:
```
What was your process to build a custom image @jmasonISP? The official Debian image claims this should already be supported, so wondering what is the missing piece here.

**Comment by suneeta-mall** [comment] 2017-08-18 00:47
We are on k8s 1.7.0 (with kops) and using amis 
> ami-b2137ea4  **k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02** us-east-1
> ami-800803e3 **k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02**  ap-southeast-2

Driver seems to be vif and not ixgbevf:
```
driver: vif
version: 
firmware-version: 
bus-info: vif-0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
admin@ip-172-20-74-151:/sbi
```

**Comment by jmasonISP** [comment] 2017-08-18 20:34
@bcorijn I found a k8s-1.7-debian-jessie AMI that I spun up on an EC2 instance in my k8s VPC. I then followed [this guide](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html) to install and enable ENA on it. Once installed I made an AMI from that instance which is what I'm using now for my kops created nodes.

**Comment by chrislovecnm** [comment] 2017-11-21 19:55
Related https://github.com/kubernetes/kops/issues/3868

**Comment by mv78** [comment] 2018-01-17 20:44
We are running Kops 1.8 with k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02 (ami-06a57e7e) where it says that ENA is enabled. However, when i run check on that instance it returns simple network:
aws ec2 describe-instance-attribute --instance-id 123 --attribute sriovNetSupport
{
    "InstanceId": "123",
    "SriovNetSupport": {
        "Value": "simple"
    }
}

I also ssh into the instance and ran lsmod | grep ixgbevf to verify that the needed module for ENA is installed and it is not there?!!!

**Comment by ottoyiu** [comment] 2018-01-18 17:18
@mv78 have you tried the debian stretch image?

**Comment by mv78** [comment] 2018-01-18 18:03
I have not, but looking at source code [https://github.com/kubernetes/kube-deploy/blob/master/imagebuilder/templates/1.8-stretch.yml](url), I dont see "ixgbevf" module included either.

**Comment by bcorijn** [comment] 2018-01-25 11:50
@mv78 that is because the base image already has it in-kernel, so there is no need to install it on top.
Your SriovNetSupport looks fine to me, if ENA is not supported that property will be empty, while a value of simple means that enhanced networking is enabled. (see [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sriov-networking.html))

It all depends on which instance type you are using, there's different ways to do ENA as described [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html). If you use one of the newer types, you need to check for the ENA driver, not the ixgbevf one.
 What instance type are you using?

**Comment by veksler** [comment] 2018-01-25 16:08
i was using m5 .

**Comment by chrislovecnm** [comment] 2018-02-13 07:30
@veksler you probably where, but you need to be using the stretch ami with m5's

**Closed** 2018-06-29 16:02 UTC
Labels: area/image, blocks-next, lifecycle/rotten
