### ISSUE TITLE
kops should support creating internal (VPC only) ELBs for apiserver / bastion

### ISSUE THREAD

**Issue by mtanski** [kubernetes/kops#1097] opened 2016-12-08 04:00 UTC
After playing around with different tools for deploying kubernetes on AWS I settled on kops. One thing I was not able to find / make work is creating internal (VPC only) ELB instances. I've searched the documentation and code in the repository. After asking on the kubernets slack instance it turns out it's not currently supported.

In the current state it's possible to create a cluster that places into a VPC only subnet (by setting private topology) but strangely the ELB that is created for the private apiserver/bastion host using a internet-facing ELB.

Our use case is running a entirely private kubernets cluster that only used other by internal services (including existing ones) and we would not like to expose the apiserver to the outside world.

**Comment by chrislovecnm** [comment] 2016-12-08 05:50
Currently, we do no have that feature.  Happy to have that feature in the model, if you would like to contribute.

**Comment by mtanski** [comment] 2016-12-08 13:42
Sure thing @chrislovecnm. I do need some guidance how to go around this, esp. the yaml conf part of it.

My initial instinct tells me to:
- make the internet-facing ELB default for backwards
- add apiserver to topology
- add elb subsection to topology.(bastion|apiserver)

```
...
    topology:                                                                                         
    bastion:
      enabled: true
      elb: { internal: true }
    apiserver:
      elb: { internal: true }
    masters: private
    nodes: private
```

Given some guidance on the approach I can go ahead and implement it.

**Comment by chrislovecnm** [comment] 2016-12-10 02:22
@kris-nova / @justinsb ... Ideas?

@mtanski the bastion is getting moved into an an instancegroup as well. Best advice I have for u is to submit a design PR and we can work through it.

**Comment by kris-nova** [comment] 2016-12-11 19:35
This might be an API change - if it is, this means we will need a design doc in the PR, and we should all be looking at 

I would wait to start this until after https://github.com/kubernetes/kops/milestone/1 which should be released this week - we will know more then what the design of this will look like :)

**Comment by justinsb** [comment] 2017-01-21 06:56
This will work in alpha4 once it is release (i.e. once the pending PRs have merged and we do the release) :-)

Here's how it should work:

`kops create cluster --topology private --channel alpha --zones us-east-1c name.example.com --networking kopeio-vxlan`

If you then `kops edit cluster name.example.com`, there will be a section

```
spec:
  api:
    loadBalancer:
      type: Public
```

which you'll have to change to

```
spec:
  api:
    loadBalancer:
      type: Internal
```

And then `kops update cluster` etc as usual

**Comment by justinsb** [comment] 2017-01-29 06:41
This should work in kops 1.5.0 beta1, which is now released, so I'm going to close.  But if this is not fixed in 1.5.0 beta1 or later, please comment or reopen.

**Closed by justinsb** 2017-01-29 06:41 UTC
Labels: should-be-fixed-in-alpha4

**Comment by jamesgoodhouse** [comment] 2017-02-13 20:51
Setting loadBalancer type to Internal appears to only affect the API server, and not the bastion server. Is this the intended behavior, or maybe I'm misunderstanding how one would set the bastion LB to be internal also?

**Comment by dlouzan** [comment] 2017-03-13 16:32
Though justinsb's message states that this should be working since kops 1.5.0 beta1, using kops 1.5.1 I'm not able to switch an automatically created public ELB to an internal ELB, I get the following error after editing my cluster and triggering a cluster update:

```
I0313 15:30:12.011348   21686 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)
I0313 15:30:22.011602   21686 executor.go:91] Tasks: 59 done / 62 total; 1 can run
W0313 15:30:22.069016   21686 executor.go:109] error running task "LoadBalancer/api.k8s.sob-prod.local" (7m8s remaining to succeed): subnet changes on LoadBalancer not yet implemented: actual=[subnet-c2c0a8aa] -> expected=[subnet-d5c0a8bd]
I0313 15:30:22.069119   21686 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)
```

My configuration is as follows:

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2017-02-22T13:55:14Z"
  name: k8s.sob-prod.local
spec:
  api:
    loadBalancer:
      type: Public
  channel: stable
  cloudProvider: aws
  configBase: s3://<hidden>
  dnsZone: <hidden>
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.5.2
  masterInternalName: api.internal.k8s.sob-prod.local
  masterPublicName: api.k8s.sob-prod.local
  networkCIDR: 10.110.0.0/16
  networkID: vpc-f2c06d9a
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.110.8.0/24
    egress: nat-02d62e637dd9b7838
    id: subnet-d5c0a8bd
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 10.110.0.0/24
    id: subnet-c2c0a8aa
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
```

I am trying to change the api.loadBalancer from Public to Internal

Am I missing anything?

**Comment by alok87** [comment] 2017-03-14 09:04
@justinsb can we use the api load balancer type as private in kops version `Version 1.5.1 (git-01deca8)` I am getting this error while using that `error building tasks: unhandled LoadBalancer type "Private"`

**Comment by callum-p** [comment] 2017-04-04 05:51
If you get this error you need to delete your old internet-facing ELB.

**Comment by fschuh** [comment] 2017-05-16 04:05
Using kops 1.6.0-beta.1 and having the same issue as @dlouzan 

```
I0516 04:01:17.933213   14024 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)
I0516 04:01:27.933523   14024 executor.go:91] Tasks: 90 done / 93 total; 1 can run
W0516 04:01:28.325398   14024 executor.go:109] error running task "LoadBalancer/api.mycluster-pvt.kube-test.io" (9m48s remaining to succeed): subnet changes on LoadBalancer not yet implemented: actual=[subnet-39d4b250] -> expected=[subnet-50d7b139]
```

I did a `kops edit cluster` and have changed my LoadBalancer type from Public to Internal as instructed.
The error happens after attempting a cluster update.

Any updates on this?

**Comment by fschuh** [comment] 2017-05-16 04:19
I missed the comment by @callum-p.

I can confirm that deleting the internet-facing ELB will cause `kops update cluster` to create an internal ELB with no master nodes on it, and the error message is gone.

This seems hacky though, is this the only solution?
Might as well **not** create an internet-facing ELB instead then, or at least add a command line options to kops to do so.

Having to delete/recreate the ELB and then manually add the master to it sure is ugly.
A private topology should definitely not come with a public internet-facing ELB for the master.

I suppose this is a bug and the current behavior is incorrect?
Can anybody confirm?

**Comment by callum-p** [comment] 2017-05-16 04:21
I pass through my cluster config to kops and it creates an internal ALB using this spec.  If you do this from the start you won't run into the issue.  You only run into the issue when changing from public to private.
`---
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2017-03-31T05:29:53Z"
  name: $CLUSTER_NAME
spec:
  api:
    loadBalancer:
      type: Internal`

**Comment by tobstarr** [comment] 2018-01-09 14:08
Is this only working for network topology private? I tried this with topology public but am getting this error here:

`W0109 15:02:44.591167   17833 executor.go:109] error running task "LoadBalancer/api.v1.wunderscale.com" (9m58s remaining to succeed): Field is required: Subnets`

I tried to add a subnets field to `api.loadBalancer` and `api` but both were not accepted.

What I am trying to achieve is to setup a cluster with kops which is not using any public IPs at all (not for the api server and also not for the LoadBalancers) but instead just access the cluster through via a VPN gateway. I found the bastion approach to be a little bit to complicated for what I want to have.

**Comment by olemarkus** [comment] 2018-01-31 11:50
Looks like. See #3433

**Comment by hustshawn** [comment] 2018-12-06 10:23
Hi all, may I know is it possible to create application-level internal loadbalancer? Currently, if the service defined with `LoadBalancer` type, it will just create a public loadbalancer, which will expose to the outside network of my VPC.

In my case, I need an internal loadbalancer which expose the service out of the k8s cluster, but still accessible throughout the VPC scope. For example, my lambda function may need to communicate with the service that inside of the k8s cluster.
