### ISSUE TITLE
Error creating cluster: "found duplicate tasks with name"

### ISSUE THREAD

**Issue by itskingori** [kubernetes/kops#1415] opened 2017-01-09 16:05 UTC
**Version of kops**
```
$ kops version
Version 1.5.0-alpha1
```

Ps: Specific commit is 2dbda04.

---

**Step 1: Initialize the cluster**

```
$ kops create cluster \
  --name=production.kubernetes.example.com \
  --state=s3://example.kubernetes \
  --bastion=true \
  --cloud=aws \
  --dns-zone=production.kubernetes.example.com \
  --master-zones=us-east-1c,us-east-1d,us-east-1e \
  --master-size=m4.large \
  --networking=weave \
  --node-size=m4.large \
  --node-count=3 \
  --network-cidr=10.80.0.0/16 \
  --out=. \
  --ssh-public-key=~/.ssh/kubernetes_rsa.pub \
  --target=terraform \
  --topology=private \
  --zones=us-east-1c,us-east-1d,us-east-1e
```

**Step 2: Edited the cluster**

```
$ kops edit cluster \
  --name=production.kubernetes.example.com \
  --state=s3://example.kubernetes
```

```diff
spec:
  topology:
    bastion:
-      bastionPublicName: bastion-production.kubernetes.example.com
+      bastionPublicName: bastion.production.kubernetes.example.com
```

**Step 3: Output edits to Terraform**

```
$ kops update cluster \
  --name=production.kubernetes.example.com \
  --state=s3://example.kubernetes \
  --out=. \
  --target=terraform
```

---

This is the error I get:

```
F0109 17:57:11.085785   34106 task.go:55] found duplicate tasks with name "DNSZone/production.kubernetes.example.com": *awstasks.DNSZone {"Name":"production.kubernetes.example.com","DNSName":"production.kubernetes.example.com","ZoneID":null,"Private":false,"PrivateVPC":null} and *awstasks.DNSZone {"Name":"production.kubernetes.example.com","DNSName":"production.kubernetes.example.com","ZoneID":null,"Private":false,"PrivateVPC":null}
```

**Comment by kris-nova** [comment] 2017-01-09 16:07
Duplicate of https://github.com/kubernetes/kops/issues/1374 and https://github.com/kubernetes/kops/issues/1410

Fixed in https://github.com/kubernetes/kops/pull/1345

@itskingori 

Can you please build from HEAD now that this has been merged and try again?

**Closed by kris-nova** 2017-01-09 16:07 UTC

**Comment by itskingori** [comment] 2017-01-09 16:11
@kris-nova Ok. 👍

Sorry about that 🙈 ... for once I didn't check. I was testing your new bastion fixes but I'd branched off at https://github.com/kubernetes/kops/commit/2dbda04f0de331f40dc695e4a5453ae2fd4ec2bc a few hours ago. It didn't quite look related to the bastion issue so didn't want to pollute https://github.com/kubernetes/kops/issues/1322.

**Comment by itskingori** [comment] 2017-01-09 16:27
I can confirm latest version solves this problem (dfed37e).

Thanks. 🙌
