### ISSUE TITLE
Shouldn't change existing resource names

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes/kops#1434] opened 2017-01-10 18:49 UTC
```
$ kops version
Version git-5f066f58
```

Created with these options:
```
	kops create cluster \
                --name prod.us-west-1.aws.k8s \
                --node-count 10 \
                --zones us-west-1a,us-west-1b \
                --master-zones us-west-1a \
                --node-size m4.large \
                --master-size m4.large \
                --topology private \
                --networking calico \
                --vpc vpc-xxxxxxxxxx \
                --network-cidr 10.1.0.0/16 \
                --state s3://kops-k8s-state-store
```

Noticed this when we were auditing the changes for our production cluster:
```
Will modify resources:
  DNSZone/ZCOTIIWU0FE1A
        Private                  true -> false

  VPC/prod.us-west-1.aws.k8s
        Name                     prod-us-west-1 -> prod.us-west-1.aws.k8s

  InternetGateway/prod.us-west-1.aws.k8s
        Name                     <nil> -> prod.us-west-1.aws.k8s
```

I'm not sure why it would change the DNSZone from private to public with `--topology private` either...

**Comment by yissachar** [comment] 2017-01-11 16:26
Dupe of https://github.com/kubernetes/kops/issues/476

**Comment by kris-nova** [comment] 2017-01-11 16:53
Can we close then?

**Comment by chrislovecnm** [comment] 2017-01-11 22:03
Closing

**Closed by chrislovecnm** 2017-01-11 22:03 UTC
