### ISSUE TITLE
Error building OpenStack authenticated client: Authentication failed

### ISSUE THREAD

**Issue by abyrne55** [kubernetes/kops#7921] opened 2019-11-12 22:32 UTC
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`1.16.0-alpha.1 (git-ea779042c)`. I was also able to reproduce with `1.14.1 (git-b7c25f9a9)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
n/a (creating a new cluster, no version specified)

**3. What cloud provider are you using?**
OpenStack (Pike)

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
source openstack.rc
export OS_USER_DOMAIN_NAME="Default"
export KOPS_STATE_STORE=swift://sid-moc-kops
kops create cluster \
  --cloud openstack \
  --name sid-moc.n-x.win \
  --state ${KOPS_STATE_STORE} \
  --zones nova \
  --network-cidr 10.0.0.0/24 \
  --image "Ubuntu 18 LTS" \
  --master-count=1 \
  --node-count=2 \
  --node-size m1.small \
  --master-size m1.large \
  --etcd-storage-type default \
  --api-loadbalancer-type public \
  --topology private \
  --bastion \
  --ssh-public-key ~/.ssh/id_rsa.pub \
  --networking weave \
  --os-dns-servers=8.8.8.8,8.8.4.4 \
  --os-ext-net "external"
```

**5. What happened after the commands executed?**
```
I1112 17:21:42.340212    8363 create_cluster.go:1568] Using SSH public key: /home/ubuntu/.ssh/id_rsa.pub

error building path for "swift://sid-moc-kops": error building openstack authenticated client: Authentication failed
```
**6. What did you expect to happen?**
Successful creation of a cluster as explained in the [OpenStack Getting Started guide](https://github.com/kubernetes/kops/blob/master/docs/getting_started/openstack.md).

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
n/a (no cluster created)

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
```
I1112 17:21:46.646436    8480 create_cluster.go:1568] Using SSH public key: /home/ubuntu/.ssh/id_rsa.pub
I1112 17:21:46.648231    8480 factory.go:68] state store swift://sid-moc-kops
I1112 17:21:46.649790    8480 swiftfs.go:66] authenticating to keystone

error building path for "swift://sid-moc-kops": error building openstack authenticated client: Authentication failed
```
**9. Anything else do we need to know?**
After running `source openstack.rc` and `export OS_USER_DOMAIN_NAME="Default"`, I'm able to use the `openstack` CLI client without issue, so my environment should be set correctly. I've tried using both Identity API v2 and v3 openstack.rc files. One potential source of issues I've identified is that my OpenStack cluster's Swift application is hosted on a different subdomain than the rest of the cluster (e.g. API for Image, Volume, Identity, etc. is on openstack.example.com, but Swift is on os-swift.example.com).

**Comment by zetaab** [comment] 2019-11-15 20:26
you should run `export OS_DOMAIN_NAME` instead of os_user_domain_name

**Comment by kesslerdev** [comment] 2019-11-19 09:42
hello,
i have the same problem even if `OS_DOMAIN_NAME=MyaccountName` is set.
with several versions of kops (from 1.14)

**Comment by zetaab** [comment] 2019-11-19 17:13
difficult to say what is wrong with this amount of information. 

The error is coming from row https://github.com/kubernetes/kops/blob/release-1.14/util/pkg/vfs/swiftfs.go#L70 so it takes parameters from https://github.com/kubernetes/kops/blob/release-1.14/util/pkg/vfs/swiftfs.go#L54 and https://github.com/kubernetes/kops/blob/release-1.14/util/pkg/vfs/swiftfs.go#L49

I do not have swift so I cannot debug what is wrong with it, or is it just some environments.

This takes credentials from environment variables https://github.com/kubernetes/kops/blob/release-1.14/util/pkg/vfs/swiftfs.go#L136 which is using function from gophercloud. There is not really any custom code in that part of the code.

**Comment by zetaab** [comment] 2019-11-19 17:19
btw do you have some special characters in password? It can be one problem

**Comment by kesslerdev** [comment] 2019-11-20 09:17
yes i've a `?` in my password

**Comment by zetaab** [comment] 2019-11-20 13:14
our openstack admins are going to install swift in this week I hope, so lets see can I reproduce this problem

**Comment by zetaab** [comment] 2019-11-21 09:29
I cannot reproduce this 

```
% source sose-test4-openrc.sh
Please enter your OpenStack Password for project sose-test4 as user myuser@company.com:
% export KOPS_STATE_STORE=swift://sosetest4
% kops get clusters

no clusters found

% env|grep KOPS
KOPS_STATE_STORE=swift://sosetest4
 % env|grep OS
OS_AUTH_URL=https://openstack.com:13000/v3
OS_PROJECT_ID=8f78d18bc329459782aa3b0680c64f7a
OS_PROJECT_NAME=sose-test4
OS_USER_DOMAIN_NAME=userdomain
OS_PROJECT_DOMAIN_ID=default
OS_USERNAME=myuser@company.com
OS_PASSWORD=toosecret
OS_REGION_NAME=regionOne
OS_INTERFACE=public
OS_IDENTITY_API_VERSION=3
OS_DOMAIN_NAME=userdomain
```

Is your object store containers located under same openstack project?

**Comment by kesslerdev** [comment] 2019-11-27 13:00
we are using the v3 api of keystone with project scope. It 's supported by kops ?

**Comment by kesslerdev** [comment] 2019-12-16 13:54
when i use application credentials it's works ! `OS_AUTH_TYPE=v3applicationcredential`

but also a problem first auth (for swift) is using `OS_CACERT` correctly but other call fails with an invalid authority (cacert not used) 
a workaround is to install ca certificate globally 
```shell
cp ${OS_CACERT} /usr/local/share/ca-certificates/cabundle.pem
update-ca-certificates
```

**Comment by zetaab** [comment] 2019-12-16 22:27
kops does not handle insecure certificates currently. The workaround for that is to install cabundle in instancegroup additionalUserData  https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/instancegroup.go#L145

**Comment by vishalya** [comment] 2020-01-03 15:20
I also get the same error.
Openstack doesn't really require to have to have OS_DOMAIN_NAME to authenticate as per this doc
https://docs.openstack.org/python-openstackclient/pike/cli/authentication.html

**Comment by vishalya** [comment] 2020-01-03 21:18
I was looking at https://github.com/kubernetes/kops/blob/master/vendor/github.com/gophercloud/gophercloud/auth_options.go#L310.
If I set the env variable OS_DOMAIN_NAME to the value from OS_USER_DOMAIN_NAME, (in my case, the value is default), it goes further along.

**Comment by MPV** [comment] 2020-04-05 08:34
I'm hoping this could be resolved by upgrading the Gophercloud implementation, as mentioned in #8793.

**Closed** 2020-06-04 09:56 UTC
Labels: lifecycle/rotten
