### ISSUE TITLE
Kops failng when custom domain name is used in DHCP instead of ec2.internal which is default in aws

### ISSUE THREAD

**Issue by musunuru** [kubernetes/kops#4768] opened 2018-03-23 22:45 UTC
Thanks for submitting an issue! Please fill in as much of the template below as
you can.

------------- BUG REPORT TEMPLATE --------------------

1. What `kops` version are you running? The command `kops version`, will display
 this information.
Version 1.8.0 (git-5099bc5)
2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
3. What cloud provider are you using?
aws
4. What commands did you run?  What is the simplest way to reproduce this issue?
Spin up kops cluster in aws with custom DHCP hosted name
5. What happened after the commands executed?
kops validate cluster failed its not showing any nodes
6. What did you expect to happen?
kops validate cluster should show nodes
7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.

9. Anything else do we need to know?
When DHCP is changed to ec2.internal validate cluster is success.

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.

2. Feel free to provide a design supporting your feature request.

**Comment by huang-jy** [comment] 2018-03-26 17:34
Is your domain hosted in Route 53?

**Comment by huang-jy** [comment] 2018-03-26 18:21
A few basic troubleshooting questions:

1. Are your instances spot instances?
2. Have you waited for DNS to propagate?
3. Did `kops create cluster` complete successfully?
4. Did you run `kops update` and/or `kops rolling-update`?
5. Can you see the instances show up on EC2?
6. Can you SSH into them? (you may need to use bastions if you have internal IPs and no VPC tunnel)
7. Did any Route 53 entries get created? If so what ones? Are any/all of them placeholder IPs?
8. What does `kops validate` come back with? Does it error?
9. Have you tried `kops export config` to switch context to your cluster?

**Comment by dzoeteman** [comment] 2018-03-27 07:54
Do you run both your custom domain and .internal? We are running that and having no issue.

`our.domain eu-central-1.compute.internal`

**Comment by musunuru** [comment] 2018-03-27 20:33
@dzoeteman we have custom domain in DHCP set, I even tried by keeping but no luck.

**Comment by musunuru** [comment] 2018-03-27 20:36
@huang-jy 
Are your instances spot instances?
No On Demand
Have you waited for DNS to propagate?
Yes
Did kops create cluster complete successfully?
Yes
Did you run kops update and/or kops rolling-update?
update
Can you see the instances show up on EC2?
yes 
Can you SSH into them? (you may need to use bastions if you have internal IPs and no VPC tunnel)
yes 
Did any Route 53 entries get created? If so what ones? Are any/all of them placeholder IPs?
Yes created and pointed to Master IP
What does kops validate come back with? Does it error?
NODE STATUS
NAME	ROLE	READY

Validation Failed
Ready Master(s) 0 out of 1.
Ready Node(s) 0 out of 1.

No nodes found in validationCluster
Have you tried kops export config to switch context to your cluster?
No

**Comment by dzoeteman** [comment] 2018-03-27 20:40
Can you check the logs of the instances that are spinned up? Specifically the syslog, which should have the kubelet logs in it. It will probably have the reason they are not being registered in the cluster.

**Comment by huang-jy** [comment] 2018-03-27 20:40
Re your last point -- do you / have you use more than one cluster?

**Comment by musunuru** [comment] 2018-03-27 22:29
@huang-jy No, I used only cluster

**Comment by musunuru** [comment] 2018-03-27 22:29
@dzoeteman Sure I will look into it.

**Comment by huang-jy** [comment] 2018-03-28 04:15
What was the create command you used @musunuru? And can we have your cluster definition (you can redact sensitive content if needed)

**Comment by musunuru** [comment] 2018-03-28 16:16
@huang-jy Got the issue resolved, In DHCP we have domain name as "company.com." by changing it to "company.com" it worked fine..

**Comment by huang-jy** [comment] 2018-03-28 16:38
To confirm - you had a trailing dot?

**Comment by musunuru** [comment] 2018-03-28 16:50
Yes trailing dot caused the issue

**Comment by huang-jy** [comment] 2018-03-28 16:58
Thanks. If the issue is solved, please close the issue.

@chrislovecnm -- not sure if there's a knowledge base or similar on here, but might be worth adding/creating one with common issues.

**Closed** 2018-03-28 16:59 UTC
