### ISSUE TITLE
Create a setting that allows the user to disable t3 unlimited mode for t3 instance group

### ISSUE THREAD

**Issue by Pehesi97** [kubernetes/kops#6284] opened 2019-01-02 11:49 UTC
Some autoscalers rely on CPU usage to define their behavior. When a t3 instance is launched, the unlimited mode is enabled by default on it. This results on unpredicted costs and inconsistent usage analysis.
It would be good to have a setting that disables unlimited mode for t3 instance groups. Is it possible?

**Comment by erdii** [comment] 2019-03-15 13:24
This features would be really nice to have!

**Comment by david-in-perth** [comment] 2019-05-16 05:17
This is essentially a duplicate of https://github.com/kubernetes/kops/issues/4032. In short: Allow credit specification for T2 and T3 instances. There's probably no need for a separate ticket.

**Closed** 2020-01-11 19:30 UTC
Labels: lifecycle/rotten

**Comment by iamakulov** [comment] 2021-03-05 15:43
Looks like this was just implemented in https://github.com/kubernetes/kops/pull/10934.
