### ISSUE TITLE
Kubelet 'failed to get cgroup stats for "/system.slice/kubelet.service"' error messages

### ISSUE THREAD

**Issue by jkemp101** [kubernetes/kops#4049] opened 2017-12-12 22:25 UTC
1. What `kops` version are you running? The command `kops version`, will display
 this information.
`Version 1.8.0 (git-5099bc5)`

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.9-dirty", GitCommit:"7f63532e4ff4fbc7cacd96f6a95b50a49a2dc41b", GitTreeState:"dirty", BuildDate:"2017-10-26T22:33:15Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

Provisioned a 1.8.4 cluster by:

   * Creating a basic cluster with `kops`
   * Exporting that cluster to a manifest file
   * Added my changes to manfiest
   * Generate terraform configs
  
5. What happened after the commands executed?
I get the following error message in the daemon logs unless I add the following to the manifest:
```
  kubelet:
    kubeletCgroups: "/systemd/system.slice"
    runtimeCgroups: "/systemd/system.slice"
  masterKubelet:
    kubeletCgroups: "/systemd/system.slice"
    runtimeCgroups: "/systemd/system.slice"
```

```
Dec 12 22:12:14 ip-172-20-64-61 kubelet[30742]: E1212 22:12:14.322073   30742 summary.go:92] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
```

6. What did you expect to happen?
No error messages

**Comment by chrislovecnm** [comment] 2017-12-14 22:05
@blakebarnett ideas?

**Comment by blakebarnett** [comment] 2017-12-14 22:13
Yes, dupe of https://github.com/kubernetes/kops/issues/1869

**Comment by jkemp101** [comment] 2017-12-14 22:29
@blakebarnett This repeating error message about collecting stats is a duplicate of setting kubelet reserved resources?

**Comment by blakebarnett** [comment] 2017-12-14 22:59
oh sorry, I misread the errors.  I believe it's because the base image doesn't have proper cgroups configured though, which is ultimately the same problem as #1869

**Comment by jkemp101** [comment] 2017-12-14 23:08
>  base image doesn't have proper cgroups configured

Well that doesn't sound good. I guess my first question is if the `kubeletCgroups` and `runtimeCgroups` settings I'm using is a safe workaround or is this a bigger issue?  I got that fix from the stackoverflow thread mentioned in this issue https://github.com/kubernetes/kubernetes/issues/53960 but I didn't really research if this is a good fix or if I should be more concerned.

I should have mentioned the cluster was built with `k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02`

**Comment by chrislovecnm** [comment] 2017-12-15 22:38
How about we close this and continue on the other issue?

**Comment by chrislovecnm** [comment] 2017-12-15 22:39
Never mind the other issue is closed. See if I can find the one I am thinking of

**Comment by blakebarnett** [comment] 2017-12-15 23:31
This one? https://github.com/kubernetes/kops/issues/3762

**Comment by chrislovecnm** [comment] 2017-12-16 01:01
Closing as a duplicate of #3762

**Comment by jkemp101** [comment] 2017-12-16 01:13
We can close this but I wouldn't call it a duplicate of #3762 unless you change the title.  That issue is a recommendation to follow best practices, this is an error message.  I'm trying to prepare new 1.8 clusters for critical production workloads.  Can someone clarify if:

1. This error message is benign and should be ignored
1. The listed workaround using `kubeletCgroups` and `runtimeCgroups` should be used until #3762 is addressed.
1. We aren't sure what the impact of this error message is and therefore clusters experiencing this error message should probably not be used in a production environment.

**Comment by chrislovecnm** [comment] 2017-12-16 01:56
/cc @itskingori @gambol99 @justinsb

Added a couple of gurus to see if they can help

**Comment by blakebarnett** [comment] 2017-12-16 02:03
I think his solution of adding:
```  kubelet:
    kubeletCgroups: "/systemd/system.slice"
    runtimeCgroups: "/systemd/system.slice"
  masterKubelet:
    kubeletCgroups: "/systemd/system.slice"
    runtimeCgroups: "/systemd/system.slice"``` 

as a default seems sane, this slice does exist and may help provide some metrics (I'm not sure where they're exposed, or what we're missing without them yet)

**Comment by jkemp101** [comment] 2017-12-18 21:00
Thanks for getting back to this quickly. Sounds like I should stick with my current workaround until other fixes are in place. This issue can be closed if there aren't any other suggestions.

**Comment by blakebarnett** [comment] 2017-12-18 21:03
Let's keep it open until we either get the defaults / docs updated or come up with a better solution.

**Comment by mercantiandrea** [comment] 2017-12-30 10:40
this workaround works also on AWS default image for kops (debian based)

`sudo vim /etc/sysconfig/kubelet`

add at the end of DAEMON_ARGS string:

` --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice`

finally:

`sudo systemctl restart kubelet`

**Comment by jordanjennings** [comment] 2018-01-03 22:08
Thanks for the workaround! One thing that I noticed it fixes is the reported docker version from `kubectl get nodes -o wide`

First node has the workaround, second doesn't:

```
NAME                             STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION   CONTAINER-RUNTIME
ip-10-244-115-162.ec2.internal   Ready     node      23m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.4.102-k8s      docker://17.9.0
ip-10-244-117-51.ec2.internal    Ready     node      21h       v1.8.5    <none>        Debian GNU/Linux 8 (jessie)   4.4.102-k8s      docker://Unknown
```

**Comment by zparnold** [comment] 2018-02-28 19:02
I can codify @mercantiandrea's proposed solution and issue a PR. Give me a few moments...or days. :)

**Comment by oliverseal** [comment] 2018-04-21 21:46
I'm using terraform output to spin up several clusters on AWS and this has been a source of aggravation having to go to each instance and edit the /etc/sysconfig/kubelet file. It's made aws auto scaling groups almost useless.

**Comment by mercantiandrea** [comment] 2018-04-22 19:40
@oliverseal You can modify the user-data bash script in the terraform template. It is encoded in base64 but you can easily decode, modify and finally encode again.

**Comment by itskingori** [comment] 2018-04-30 05:52
@mercantiandrea @oliverseal Seems you're doing manually what's done automatically for you, i.e. https://github.com/kubernetes/kops/issues/4049#issuecomment-352152838. You only need to add these when you edit your cluster:

```yaml
spec:
  kubelet:
    kubeletCgroups: "/systemd/system.slice"
    runtimeCgroups: "/systemd/system.slice"
  masterKubelet:
    kubeletCgroups: "/systemd/system.slice"
    runtimeCgroups: "/systemd/system.slice"
```

**Comment by justinsb** [comment] 2018-07-20 16:21
We should fix this in 1.11

**Comment by Guezennec** [comment] 2018-08-02 19:25
hi all 
not fixed in 1.11 :-( , just setup release 1.11 and still have the bug , the config file has changed it's now a yaml file , where we can add the workaround thanks

**Comment by tsuna** [comment] 2018-09-06 07:55
After applying the workaround I now see this seemingly useless log message every 5min:
```
container_manager_linux.go:427] [ContainerManager]: Discovered runtime cgroups name: /systemd/system.slice
```

**Comment by rekcah78** [comment] 2018-09-17 09:47
@Guezennec maybe @justinsb say kops 1.11 not k8s 1.11, and kops 1.11 is not yet released.

**Comment by tsuna** [comment] 2019-02-12 22:39
Not sure if this expected but I still see this every 5min, although the workaround is not needed anymore (am on k8s 1.11.7 now with kops 1.12-alpha):
```
I0212 22:31:26.146763    3334 container_manager_linux.go:428] [ContainerManager]: Discovered runtime cgroups name: /systemd/system.slice
```

**Closed** 2019-04-13 05:17 UTC
Labels: lifecycle/rotten
