### ISSUE TITLE
Not able to create a gossip-based cluster using 1.6.2

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kops#2793] opened 2017-06-22 03:38 UTC
Using kops 1.6.2 and trying to create a cluster as:

```
kops create cluster cluster.k8s.local --zones us-east-1c
```

And getting the error:

```
I0622 05:35:23.148299   75577 create_cluster.go:654] Inferred --cloud=aws from zone "us-east-1c"
I0622 05:35:23.148658   75577 create_cluster.go:833] Using SSH public key: /Users/argu/.ssh/id_rsa.pub
I0622 05:35:23.953756   75577 subnets.go:183] Assigned CIDR 172.20.32.0/19 to subnet us-east-1c
Previewing changes that will be made:

I0622 05:35:28.546724   75577 apply_cluster.go:396] Gossip DNS: skipping DNS validation
F0622 05:35:28.560277   75577 topological_sort.go:54] dependency not found: *awstasks.DNSZone null
```

**Comment by arun-gupta** [comment] 2017-06-22 07:38
Two issues:

- Using an older version of kops
- `m3.medium` is not available in `us-east-1c`. The master node gave the following error message:

```
Launching a new EC2 instance. Status Reason: Your requested instance type (m3.medium) is not supported in your requested Availability Zone (us-east-1c). Please retry your request by not specifying an Availability Zone or choosing us-east-1d, us-east-1a, us-east-1b, us-east-1e. Launching EC2 instance failed.
```

Another EC2 instance of `m3.medium` could be easily started in `us-east-1c`.

Restarting the cluster as following worked:

```
kops create cluster cluster.k8s.local --zones us-east-1a --yes
```

**Comment by chrislovecnm** [comment] 2017-06-30 22:42
We have a PR in to the issue of trying a machine type that does not exist. This is a duplicate of that issue.

Can we close?

**Comment by arun-gupta** [comment] 2017-06-30 23:03
Close after linking the issue?

**Comment by chrislovecnm** [comment] 2017-07-01 00:26
https://github.com/kubernetes/kops/issues/2811

**Closed by chrislovecnm** 2017-07-01 00:26 UTC
