### ISSUE TITLE
Kops with the new AWS DC.

### ISSUE THREAD

**Issue by adiri** [kubernetes/kops#1109] opened 2016-12-09 02:39 UTC
Amazon just announced a new data centre in Canada (ca-central-1a).

I tried to bootstrap a new cluster but I get exceptions since the images are not there:

```
W1208 20:00:15.889318   89880 executor.go:100] error running task "launchConfiguration/nodes.k8s.ca-central-1.CLUSTER_NAME": could not find Image for "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
```

**Comment by chrislovecnm** [comment] 2016-12-09 03:23
O Cananda... The Canadian had to go there

**Comment by adiri** [comment] 2016-12-09 03:46
:)

**Comment by chrislovecnm** [comment] 2016-12-09 21:45
https://github.com/kubernetes/kops/pull/1108 should fix this

**Comment by chrislovecnm** [comment] 2016-12-09 21:54
@adiri k8s will not support the zone till 1.5.  We have a patch going through for it ;)

**Comment by adiri** [comment] 2016-12-09 21:56
@chrislovecnm Okay :) I guess me and the other Canadians will wait :)

**Comment by chrislovecnm** [comment] 2016-12-09 22:05
So I am incorrect.  Until https://github.com/kubernetes/kubernetes/issues/35014 gets address this is not fixed.  We need to get an update in for https://github.com/kubernetes/kubernetes/blob/7760c2f5fa004fc7e1a1be631ce423a35e09400d/pkg/credentialprovider/aws/aws_credentials.go#L35, and also fix https://github.com/kubernetes/kubernetes/issues/35014

We 'should' be able to backport a change to aws_credentials.go

**Comment by tanner-bruce** [comment] 2017-01-09 18:25
Is there an ETA on this, we are looking to start a new cluster in the CA zone.

**Comment by yuzhenmi** [comment] 2017-01-09 19:57
Same here, really looking forward to this!

**Comment by justinsb** [comment] 2017-01-17 06:37
This should be working in Canada now.  If you specify `--channel alpha` you get k8s 1.5.2 and an image that exists in ca-central-1.  This _should_ work with kops 1.4.4, but will work better with kops 1.5 alphas.

**Comment by tanner-bruce** [comment] 2017-01-17 16:13
I can confirm it is working since alpha3 although I haven't tried alpha4

**Comment by chrislovecnm** [comment] 2017-01-17 17:54
Can we close?

**Comment by adiri** [comment] 2017-01-20 05:35
Yes, tested with --channel alpha and it seems to work.

**Comment by chrislovecnm** [comment] 2017-01-20 05:55
Closing

**Closed by chrislovecnm** 2017-01-20 05:55 UTC
Labels: should-be-fixed-in-alpha4
