### ISSUE TITLE
Too many endpoints in the kubernetes service

### ISSUE THREAD

**Issue by fvasco** [kubernetes/kops#12627] opened 2021-10-28 15:23 UTC
/kind bug

**1. What `kops` version are you running?**
~~~
Version 1.21.2 (git-f86388fb1ec8872b0ca1819cf98f84d18f7263a4)
~~~

**2. What Kubernetes version are you running?**
~~~
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
~~~

**3. What cloud provider are you using?**
AWS

Hello,
we got a connectivity issue with our pods.

We currently see too many IPs in the `kubernetes` endpoints, many of them reference to terminated masters.

~~~
$ kubectl describe service kubernetes -n default
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                100.64.0.1
IPs:               100.64.0.1
Port:              https  443/TCP
TargetPort:        443/TCP
Endpoints:         172.31.20.192:443,172.31.23.72:443,172.31.31.210:443 + 6 more...
Session Affinity:  ClientIP
Events:            <none>
~~~

the iptable `nat` table list all of them

~~~
# iptables -L -v -n -t nat
Chain KUBE-SVC-NPX46M4PTMTKRN6Y (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    2   120 KUBE-SEP-XXDHYK5XOL7C2QMK  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-XXDHYK5XOL7C2QMK side: source mask: 255.255.255.255
    0     0 KUBE-SEP-T2U4L34UORPF3KEV  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-T2U4L34UORPF3KEV side: source mask: 255.255.255.255
    0     0 KUBE-SEP-H7IE5EIZNU7MRD2J  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-H7IE5EIZNU7MRD2J side: source mask: 255.255.255.255
    0     0 KUBE-SEP-IKGK4FJJWDT2DVXT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-IKGK4FJJWDT2DVXT side: source mask: 255.255.255.255
    0     0 KUBE-SEP-EQDDZXJQDFIUJYBY  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-EQDDZXJQDFIUJYBY side: source mask: 255.255.255.255
    0     0 KUBE-SEP-ROWRN2NBYRGLX5XA  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-ROWRN2NBYRGLX5XA side: source mask: 255.255.255.255
    0     0 KUBE-SEP-KWMDMS2VX7LWBYQL  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-KWMDMS2VX7LWBYQL side: source mask: 255.255.255.255
    0     0 KUBE-SEP-T77HFFV4XKKCYE7Z  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-T77HFFV4XKKCYE7Z side: source mask: 255.255.255.255
    0     0 KUBE-SEP-ZWM4VW5XILR6J3V3  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-ZWM4VW5XILR6J3V3 side: source mask: 255.255.255.255
~~~

the first IP is currently unavailable and we detect error issues when a POD is starting: `Get https://100.64.0.1:443/api?timeout=32s: dial tcp 100.64.0.1:443: i/o timeout`

Is it possible to optimize the service and shrink the list to the available masters only?

**7. Please provide your cluster manifest.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
spec:
  additionalPolicies:
    node: |
      [
      { "Action": "sts:AssumeRole", "Effect": "Allow", "Resource": "*" },
      { "Action": "ec2:AssociateAddress", "Effect": "Allow", "Resource": "*" },
      { "Action": "ec2:AttachVolume", "Effect": "Allow", "Resource": "*" },
      { "Action": "ec2:DetachVolume", "Effect": "Allow", "Resource": "*" },
      { "Action": "ec2:ModifyInstanceAttribute", "Effect": "Allow", "Resource": "*" }
      ]
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-xxx/xxx
  containerRuntime: containerd
  dnsZone: xxx
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeDNS:
    provider: CoreDNS
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
    volumeStatsAggPeriod: 0s
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.21.5
  masterInternalName: k8s.internal.xxx
  masterPublicName: k8s.xxx
  metricsServer:
    enabled: true
  networkCIDR: 172.31.0.0/16
  networkID: xxx
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
    ...
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

Thank you in advance for any help,
Francesco

**Comment by olemarkus** [comment] 2021-10-30 05:50
Can you add your input to the upstream issue.
Meanwhile, I can try to reproduce this, but it may not be that easy.

**Comment by fvasco** [comment] 2021-10-30 07:45
Thank you for your effort @olemarkus!
As I said, it is possible it was an already present issue of previous upgrades.

However, I have to admit that I am not a Kubernetes Champion, so I reach to this issue using the hard way (digging into a Linux networking issue).
For our experience, in absence of a better proposal, an informational message in `kops validate cluster` should be very helpful.
A cluster with more Kubernetes endpoints than configured isn't properly valid.

So, I can imagine the rule as:

**IF** `kubernetes endpoints count` > `configured master count`
**PRINT** "kubernetes" service contains too many endpoints, this can cause connection issues to `kubernetes service host:port`. If the problem persists, see `permalink`

Moreover, I suggest modifying the first phrase of [API Server hangs after etcd restore](https://kops.sigs.k8s.io/operations/troubleshoot/#api-server-hangs-after-etcd-restore) to: After resizing an etcd cluster, restoring backup or updating kOps

Finally, if this issue can occur generally during kOps manual operations, a tool like `kops toolbox cleanup-etcd` can greatly improve the user experience.

**Comment by voriol** [comment] 2021-11-05 07:36
i have the same issue, when i upgrade from 1.21 cluster to 1.22 my kubernetes endpoint have more servers than configured masters.

i want to apply the [troubleshoot](https://kops.sigs.k8s.io/operations/troubleshoot/#api-server-hangs-after-etcd-restore) for delete the masterleases but my etcd-manager-main pod have different certificates configurated:

```
# ls /rootfs/etc/kubernetes/pki/                  
etcd-manager-events  etcd-manager-main
```

and the etcdctl connection have errors with this certificates:

```
# ./etcdctl --cacert=/rootfs/etc/kubernetes/pki/etcd-manager-main/etcd-clients-ca.crt --cert=/rootfs/etc/kubernetes/pki/etcd-manager-main/etcd-manager-client-etcd-a.crt --key=/rootfs/etc/kubernetes/pki/etcd-manager-main/etcd-manager-client-etcd-a.key --endpoints=https://127.0.0.1:4001 del --prefix /registry/masterleases/
{"level":"warn","ts":"2021-11-05T07:05:01.755Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002e0a80/#initially=[https://127.0.0.1:4001]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: authentication handshake failed: remote error: tls: bad certificate\""}
```

someone with the same problem? Thank you

**Comment by fvasco** [comment] 2021-11-09 08:39
Hi, @olemarkus,
any news on this issue?

**Comment by johngmyers** [comment] 2021-11-11 14:32
Per Office Hours, will cut a new etcd-manager and cherrypick it to 1.22 branch.

**Comment by fvasco** [comment] 2021-11-11 15:11
Great news @johngmyers, we hope it will fix!

**Comment by Kristjanf-droid** [comment] 2021-11-22 12:45
> Per Office Hours, will cut a new etcd-manager and cherrypick it to 1.22 branch.

Was this fixed in kops v.1.22.2?

**Comment by voriol** [comment] 2021-11-22 12:49
In my case not, i need to apply the [troubleshoot](https://kops.sigs.k8s.io/operations/troubleshoot/#api-server-hangs-after-etcd-restore) but from the control-plane machine, not the etcd-manager-main pod. Because the kube-apiserver certificates are not present in the pod (or i don't find it)

**Comment by olemarkus** [comment] 2021-12-01 09:16
Yes, this should have been fixed in 1.22.2. At least known causes why this happens.

The kube-apiserver certificates are not present in the etcd-manager pods. But you can connect using the certificates should be in /etcd/kubernetes/pki.

**Closed** 2021-12-01 11:17 UTC
Labels: blocks-next, kind/bug, kind/office-hours

**Comment by simonccc** [comment] 2022-05-26 08:50
I've also spent several hours battling this problem yesterday - very happy to have found this thread but  it took me a while to find the right certificates to use as I guess the naming has changed

I went into the ```etcd-manager-main``` pod - the certs were there for me in /etc/kubernetes/pki/etcd-manager

This was the right combination of paths and certs for me

```alias etcdctl='$DIRNAME/etcdctl --cacert=/etc/kubernetes/pki/etcd-manager/etcd-clients-ca.crt --cert=/etc/kubernetes/pki/etcd-manager/etcd-clients-ca.crt --key=/etc/kubernetes/pki/etcd-manager/etcd-clients-ca.key --endpoints=https://127.0.0.1:4001'```

**Comment by olemarkus** [comment] 2022-05-26 09:25
If the troubleshooting docs on this is incorrect, can you do a PR to update them with the correct paths?
