### ISSUE TITLE
[Question] Does autoscaling works on AWS? Do I need to install cluster-scaler addon?

### ISSUE THREAD

**Issue by tuananh** [kubernetes/kops#1154] opened 2016-12-14 09:23 UTC
Do I need to install [cluster-scaler addon](https://github.com/kubernetes/kops/tree/master/addons/cluster-autoscaler) for this feature to work?

I saw there is Autoscaling group created in aws account but no scaling policy defined.

**Comment by caseeker** [comment] 2016-12-14 18:18
From what I've observed, ASG works in the sense it ensures the number of instances are running, but no scaling up and down.
I'm also looking at the actual scaling part with KOPS cluster, I think https://github.com/openai/kubernetes-ec2-autoscaler this is good starting point.

**Comment by chrislovecnm** [comment] 2016-12-15 04:12
@tuananh yes that is the gist of it. never used it before, let me know.

**Comment by LEW21** [comment] 2016-12-15 10:46
Cluster-autoscaler works, except that there is a bug in the deployment template - https://github.com/kubernetes/kops/blob/master/addons/cluster-autoscaler/v1.4.0.yaml

```
image:
name: {{IMAGE}}
```

should be:

```
image: {{IMAGE}}
name: autoscaler
```

And you need to give workers IAM permissions: https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler/cloudprovider/aws#permissions

There's a problem with that last thing - I don't think you can do it with kops, and kops will override your roles on each ```kops update cluster --yes```.

**Comment by LEW21** [comment] 2016-12-15 10:47
BTW this is a duplicate of https://github.com/kubernetes/kops/issues/341.

**Comment by tuananh** [comment] 2016-12-16 01:46
@LEW21 

thanks. i have few more questions

1. How do i give IAM permission to the workers? I didn't see it anywhere in teh autoscaler addon docs

2. What would happen if i setup autoscaling policy for the ASG? Will it be gone if I update the cluster?

**Comment by chrislovecnm** [comment] 2016-12-17 22:03
Closing as duplicate

**Comment by justinsb** [comment] 2016-12-28 20:43
Closing per chris's comment (because duplicate).

**Closed by justinsb** 2016-12-28 20:43 UTC
