### ISSUE TITLE
All kops pipeline jobs failing

### ISSUE THREAD

**Issue by fejta** [kubernetes/kops#13349] opened 2022-03-08 17:40 UTC
https://prow.k8s.io/?job=*kops-pipeline*&state=failure

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-pipeline-updown-kops122/1501246191239696384

**Comment by fejta** [comment] 2022-03-08 17:42
Looks like the kops121 job is passing: https://prow.k8s.io/?job=*kops-pipeline*&state=success

Others are failing

**Comment by olemarkus** [comment] 2022-03-16 05:45
Thanks for reporting this. Our e2e runs out of OIDC providers in the account we are using. We are investigating why we suddenly started leaking those.

**Comment by olemarkus** [comment] 2022-04-03 06:45
The cause of this leakage is a change in kubetest2 where it doesn't clean up resources if tests fail. Hopefully https://github.com/kubernetes-sigs/kubetest2/pull/189 can be merged soon.

**Closed** 2022-04-11 20:33 UTC
Labels: kind/office-hours
