### ISSUE TITLE
When aws is not happy kops can hang

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kops#884] opened 2016-11-13 01:55 UTC
Something is going on with api calls.  Rate limiting or something is borked on aws side.  This is causing kops to hang.  Currently, https://github.com/kubernetes/kops/pull/882  has been hanging for 50 min.  That PR is master with a build script, and it worked like a champ 3 hrs ago.

```console
I1112 19:56:47.435106   12238 securitygrouprule.go:220] Calling EC2 AuthorizeSecurityGroupIngress
I1112 19:56:47.436022   12238 securitygrouprule.go:220] Calling EC2 AuthorizeSecurityGroupIngress
I1112 19:56:47.436639   12238 routetableassociation.go:165] Creating RouteTableAssociation
I1112 19:56:47.442196   12238 securitygrouprule.go:220] Calling EC2 AuthorizeSecurityGroupIngress
I1112 19:56:47.445190   12238 securitygrouprule.go:220] Calling EC2 AuthorizeSecurityGroupIngress
I1112 19:56:47.482703   12238 routetableassociation.go:165] Creating RouteTableAssociation
I1112 19:56:48.383868   12238 launchconfiguration.go:219] Creating AutoscalingLaunchConfiguration with Name:"master-us-west-2b.masters.k8s-private-demo.dev.aws-us-west-2.foo.io-20161113005648"
I1112 19:56:48.383954   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:48.537322   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:48.713440   12238 launchconfiguration.go:219] Creating AutoscalingLaunchConfiguration with Name:"master-us-west-2a.masters.k8s-private-demo.dev.aws-us-west-2.foo.io-20161113005648"
I1112 19:56:48.713504   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:48.719440   12238 launchconfiguration.go:219] Creating AutoscalingLaunchConfiguration with Name:"nodes.k8s-private-demo.dev.aws-us-west-2.foo.io-20161113005648"
I1112 19:56:48.719499   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:48.755554   12238 launchconfiguration.go:294] Waiting for IAM to replicate
I1112 19:56:48.755608   12238 launchconfiguration.go:295] IAM error was ValidationError: You are not authorized to perform this operation.
	status code: 400, request id: 0e75c618-a93c-11e6-8bc8-11001366cb5f
I1112 19:56:48.759176   12238 launchconfiguration.go:219] Creating AutoscalingLaunchConfiguration with Name:"master-us-west-2c.masters.k8s-private-demo.dev.aws-us-west-2.foo.io-20161113005648"
I1112 19:56:48.759233   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:48.844980   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:48.845036   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:48.852581   12238 launchconfiguration.go:101] found existing AutoscalingLaunchConfiguration: "bastion.k8s-private-demo.dev.aws-us-west-2.foo.io-20161112193535"
I1112 19:56:48.852640   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:48.966912   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:49.058655   12238 launchconfiguration.go:294] Waiting for IAM to replicate
I1112 19:56:49.058686   12238 launchconfiguration.go:295] IAM error was ValidationError: You are not authorized to perform this operation.
	status code: 400, request id: 0ea4ebdc-a93c-11e6-8dac-8520277a89db
I1112 19:56:49.093634   12238 launchconfiguration.go:219] Creating AutoscalingLaunchConfiguration with Name:"bastion.k8s-private-demo.dev.aws-us-west-2.foo.io-20161113005649"
I1112 19:56:49.093685   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
I1112 19:56:49.194781   12238 launchconfiguration.go:294] Waiting for IAM to replicate
I1112 19:56:49.194817   12238 launchconfiguration.go:295] IAM error was ValidationError: You are not authorized to perform this operation.
	status code: 400, request id: 0eb714f7-a93c-11e6-8034-135199f00f99
I1112 19:56:49.219540   12238 aws_cloud.go:507] Calling DescribeImages to resolve name "kope.io/k8s-1.4-debian-jessie-amd64-hvm-ebs-2016-10-21"
```

I will get the full logs into a private gist.

**Comment by chrislovecnm** [comment] 2016-11-13 08:28
I am fairly certain this is an issue with hitting quotas, but I am uncertain.

**Comment by justinsb** [comment] 2016-11-13 20:02
If it keeps saying

```
I1112 19:56:49.194781   12238 launchconfiguration.go:294] Waiting for IAM to replicate
I1112 19:56:49.194817   12238 launchconfiguration.go:295] IAM error was ValidationError: You are not authorized to perform this operation.
	status code: 400, request id: 0eb714f7-a93c-11e6-8034-135199f00f99
```

that looks like IAM being eventually consistent.

**Comment by chrislovecnm** [comment] 2016-11-15 20:41
I believe this is actually the droid that we are looking for:
Autoscaling Launch configurations is maxed in our zone, and also vpc limits are maxed in another.  My guess either of these locks kops.

**Comment by MrTrustor** [comment] 2016-11-18 15:15
I can confirm that IAM is eventually consistent: changes are often quickly replicated, but not always.
In this case, it seems, that as you have hit a limit (launch configs probably), AWS API returns a 400 that Kops mistakes for an IAM problem: https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/launchconfiguration.go#L289

**Comment by justinsb** [comment] 2016-12-28 04:35
We now log retries etc, so kops should not sit there silently.

Closing, but please reopen if it happens again.

**Closed by justinsb** 2016-12-28 04:35 UTC
