### ISSUE TITLE
Updating from kops v1.8.0 to master fails due to missing keyset.yaml in S3

### ISSUE THREAD

**Issue by KashifSaadat** [kubernetes/kops#4351] opened 2018-01-29 18:10 UTC
1. What `kops` version are you running?
    * Initial Cluster Build, kops v1.8.0 (5099bc5)
    * Cluster Update, kops v1.8.0 (2a5e136)

2. What Kubernetes version are you running?
    * Kubernetes v1.8.4

3. What cloud provider are you using?
    * Amazon Web Services

4. What commands did you run?
    1. Build a Kubernetes Cluster via kops ([official v1.8.0 release](https://github.com/kubernetes/kops/releases/tag/1.8.0))
    2. Build kops, protokube, nodeup from source off the master branch (I've tested off commit 2a5e136)
    3. Ensure `PROTOKUBE_IMAGE` and `NODEUP_URL` are set to the versions you have freshly built in Step 2.
    4. Run a `kops update cluster ${KOPS_CLUSTER_NAME} --yes`
    5. Run a `kops rolling-update cluster ${KOPS_CLUSTER_NAME} --yes`

5. What happened after the commands executed?
    * In the rolling-update, when a node is being rebuilt and attempting to fetch secrets from S3, it fails with below error. This occurs because the certificates / key files stored in S3 are only created when initially creating a cluster, not when updating an existing cluster.
```
s3fs.go:187] Reading file "s3://${KOPS_STATE_BUCKET}/${KOPS_CLUSTER_NAME}/pki/issued/ca/keyset.yaml"
main.go:141] got error running nodeup (will retry in 30s): error building loader: CA certificate "ca" not found
```

6. What did you expect to happen?
    * Rolling update rebuilds and validates each node successfully.

Related issue: https://github.com/kubernetes/kops/issues/4156#issuecomment-355937197
Related code:
- https://github.com/kubernetes/kops/blob/2a5e136/upup/pkg/fi/vfs_castore.go#L360
- https://github.com/kubernetes/kops/blob/2a5e136/upup/pkg/fi/vfs_castore.go#L806

**Comment by mikesplain** [comment] 2018-01-30 15:18
We actually just started getting this too, though our clusters are still under Kops 1.7 and I think a master build snuck in there somewhere in testing. Will update when I know more.

**Comment by mikesplain** [comment] 2018-01-30 16:20
Confirmed, I ran into this because I was running master kops but not up to date nodeup.  Then rolled back to 1.8.. and ran into an error that `issued/ca/keyset.yaml` had actually been generated but kops cli 1.8.0 didn't know what it was.  Deleting that, solved this issue for now.

**Comment by chrislovecnm** [comment] 2018-02-08 00:09
Closing this as a duplicate ...

**Comment by chrislovecnm** [comment] 2018-02-08 00:09
https://github.com/kubernetes/kops/issues/4156 dup

**Closed by chrislovecnm** 2018-02-08 00:09 UTC
