### ISSUE TITLE
DNS resolution has high error rate with freshly created cluster

### ISSUE THREAD

**Issue by thomaschaaf** [kubernetes/kops#5283] opened 2018-06-06 14:02 UTC
In our production environment we are experiencing many DNS timeouts.

I have created an debugging application which tries to resolve a dns name every and waits x ms between requests. https://github.com/thomaschaaf/dns-tester

We have had these problems on weave and then changed our cluster to calico but that did not resolve the problems either. 

A typical output looks like this: 

```
9500 1 '244s' '39lookups / s'
Lookup 9535 failed Error: DNS Timeout!
    at Timeout.fn [as _onTimeout] (/root/service/node_modules/await-timeout/dist/index.umd.js:112:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Lookup 9537 failed Error: DNS Timeout!
    at Timeout.fn [as _onTimeout] (/root/service/node_modules/await-timeout/dist/index.umd.js:112:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Lookup 9544 failed Error: DNS Timeout!
    at Timeout.fn [as _onTimeout] (/root/service/node_modules/await-timeout/dist/index.umd.js:112:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Lookup 9545 failed Error: DNS Timeout!
    at Timeout.fn [as _onTimeout] (/root/service/node_modules/await-timeout/dist/index.umd.js:112:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Lookup 9546 failed Error: DNS Timeout!
    at Timeout.fn [as _onTimeout] (/root/service/node_modules/await-timeout/dist/index.umd.js:112:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Lookup 9550 failed Error: DNS Timeout!
    at Timeout.fn [as _onTimeout] (/root/service/node_modules/await-timeout/dist/index.umd.js:112:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Lookup 9551 failed Error: DNS Timeout!
    at Timeout.fn [as _onTimeout] (/root/service/node_modules/await-timeout/dist/index.umd.js:112:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
9600 8 '249s' '39lookups / s'
9700 8 '252s' '38lookups / s'
9800 8 '254s' '39lookups / s'
9900 8 '257s' '39lookups / s'
10000 8 '260s' '38lookups / s'
10100 8 '262s' '39lookups / s'
Lookup 10112 failed Error: DNS Timeout!
    at Timeout.fn [as _onTimeout] (/root/service/node_modules/await-timeout/dist/index.umd.js:112:25)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
10200 9 '265s' '38lookups / s'
10300 9 '268s' '38lookups / s'
```

Basically DNS is working fine (in this case there is 1 error at 244 seconds of the program running and in the next 20 seconds we see 8 dns timeouts.

A ping between two pod on our cluster gives us no packet loss.
To test we created a fresh cluster and are also seeing the same problems there.

We're using kops Version 1.9.1 with k8s 1.9.8 and kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11.

**Comment by chrisfu** [comment] 2018-06-07 12:23
Out of curiosity @thomaschaaf, which version of Calico-node is deployed?

**Comment by thomaschaaf** [comment] 2018-06-25 13:16
@lwr20 we are using calico and not weave :) So that should not be the problem.

**Comment by lwr20** [comment] 2018-06-25 13:53
From the linked blog: "I, therefore, decided to invest an hour using iptables rather than IPVS, then replacing Weave by Calico, and CoreDNS by the older KubeDNS, in order to rule them out – no luck, the issue is still there."

Suggests to me that the problem appears in Calico too.

**Comment by mikesplain** [comment] 2018-06-26 20:48
We see similar random issues on calico as well, thanks for the tool @thomaschaaf, I'm able to replicate it much easier than other methods I've tried.  

I'll keep you updated if I find more, I haven't been able to disprove that it could be related to https://blog.quentin-machu.fr/2018/06/24/5-15s-dns-lookups-on-kubernetes/

**Comment by mikesplain** [comment] 2018-06-28 21:30
I've tested all sorts of cases, I don't think this is only related to calico. I've tried different networking configs, different AMIs (for kernel reasons), different k8s versions, different kops versions,etc. 

Likely related to this: https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-359897058

I'll keep digging

**Comment by thomaschaaf** [comment] 2018-07-05 13:34
I have tried setting up a fresh cluster again today. This time I used weave and then applied the weave-tc fix. Even then the dns times out. I don't think this fixes the problem. @Quentin-M

I logged into the machine to check that the iptables rules are applied on the node. Here is the iptables-save:
```
# Generated by iptables-save v1.6.0 on Thu Jul  5 13:24:35 2018
*mangle
:PREROUTING ACCEPT [3070:3341677]
:INPUT ACCEPT [2952:3330585]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [2658:2594296]
:POSTROUTING ACCEPT [2658:2594296]
-A POSTROUTING -p udp -m udp --dport 5353 -m string --hex-string "|00001c0001|" --algo bm --from 40 --to 65535 -m u32 --u32 "0x1c&0xf8=0x0" -j MARK --set-xmark 0x100/0x100
COMMIT
# Completed on Thu Jul  5 13:24:35 2018
# Generated by iptables-save v1.6.0 on Thu Jul  5 13:24:35 2018
*nat
:PREROUTING ACCEPT [2:212]
:INPUT ACCEPT [2:212]
:OUTPUT ACCEPT [7:420]
:POSTROUTING ACCEPT [7:420]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-JST3DGMDD6H352ZL - [0:0]
:KUBE-SEP-MVY7EV5OFJWO3K2M - [0:0]
:KUBE-SEP-RJY5SMCG5N55MUL5 - [0:0]
:KUBE-SEP-STYVSFYZJBB3LH2D - [0:0]
:KUBE-SEP-V3IEQAZFKLHEK26T - [0:0]
:KUBE-SEP-WMNRLCLTXGJNNRLO - [0:0]
:KUBE-SEP-YGCK3TMIKOIFJONX - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-ERIFXISQEP7F7OF4 - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
:WEAVE - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -j WEAVE
-A DOCKER -i docker0 -j RETURN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-JST3DGMDD6H352ZL -s 100.112.0.1/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-JST3DGMDD6H352ZL -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 100.112.0.1:53
-A KUBE-SEP-MVY7EV5OFJWO3K2M -s 10.18.3.114/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-MVY7EV5OFJWO3K2M -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-MVY7EV5OFJWO3K2M --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 10.18.3.114:443
-A KUBE-SEP-RJY5SMCG5N55MUL5 -s 10.18.5.87/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-RJY5SMCG5N55MUL5 -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-RJY5SMCG5N55MUL5 --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 10.18.5.87:443
-A KUBE-SEP-STYVSFYZJBB3LH2D -s 10.18.2.29/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-STYVSFYZJBB3LH2D -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-STYVSFYZJBB3LH2D --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 10.18.2.29:443
-A KUBE-SEP-V3IEQAZFKLHEK26T -s 100.112.0.2/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-V3IEQAZFKLHEK26T -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 100.112.0.2:53
-A KUBE-SEP-WMNRLCLTXGJNNRLO -s 100.112.0.1/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-WMNRLCLTXGJNNRLO -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 100.112.0.1:53
-A KUBE-SEP-YGCK3TMIKOIFJONX -s 100.112.0.2/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-YGCK3TMIKOIFJONX -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 100.112.0.2:53
-A KUBE-SERVICES ! -s 100.96.0.0/11 -d 100.64.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 100.64.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 100.96.0.0/11 -d 100.64.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 100.64.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES ! -s 100.96.0.0/11 -d 100.64.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 100.64.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-WMNRLCLTXGJNNRLO
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-YGCK3TMIKOIFJONX
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-STYVSFYZJBB3LH2D --mask 255.255.255.255 --rsource -j KUBE-SEP-STYVSFYZJBB3LH2D
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-MVY7EV5OFJWO3K2M --mask 255.255.255.255 --rsource -j KUBE-SEP-MVY7EV5OFJWO3K2M
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-RJY5SMCG5N55MUL5 --mask 255.255.255.255 --rsource -j KUBE-SEP-RJY5SMCG5N55MUL5
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-STYVSFYZJBB3LH2D
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-MVY7EV5OFJWO3K2M
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-RJY5SMCG5N55MUL5
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-JST3DGMDD6H352ZL
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-V3IEQAZFKLHEK26T
-A WEAVE -s 100.96.0.0/11 -d 224.0.0.0/4 -j RETURN
-A WEAVE ! -s 100.96.0.0/11 -d 100.96.0.0/11 -j MASQUERADE
-A WEAVE -s 100.96.0.0/11 ! -d 100.96.0.0/11 -j MASQUERADE
COMMIT
# Completed on Thu Jul  5 13:24:35 2018
# Generated by iptables-save v1.6.0 on Thu Jul  5 13:24:35 2018
*filter
:INPUT ACCEPT [108:73967]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [106:65061]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-FORWARD - [0:0]
:KUBE-SERVICES - [0:0]
:WEAVE-NPC - [0:0]
:WEAVE-NPC-DEFAULT - [0:0]
:WEAVE-NPC-INGRESS - [0:0]
-A INPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A INPUT -j KUBE-FIREWALL
-A FORWARD -o weave -m comment --comment "NOTE: this must go before \'-j KUBE-FORWARD\'" -j WEAVE-NPC
-A FORWARD -o weave -m state --state NEW -j NFLOG --nflog-group 86
-A FORWARD -o weave -j DROP
-A FORWARD -i weave ! -o weave -j ACCEPT
-A FORWARD -o weave -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -m comment --comment "kubernetes forward rules" -j KUBE-FORWARD
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -p tcp -j ACCEPT
-A FORWARD -p udp -j ACCEPT
-A FORWARD -p icmp -j ACCEPT
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -s 100.96.0.0/11 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -d 100.96.0.0/11 -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A WEAVE-NPC -m state --state RELATED,ESTABLISHED -j ACCEPT
-A WEAVE-NPC -d 224.0.0.0/4 -j ACCEPT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-DEFAULT
-A WEAVE-NPC -m state --state NEW -j WEAVE-NPC-INGRESS
-A WEAVE-NPC -m set ! --match-set weave-local-pods dst -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-E.1.0W^NGSp]0_t5WwH/]gX@L dst -m comment --comment "DefaultAllow isolation for namespace: default" -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-0EHD/vdN#O4]V?o4Tx7kS;APH dst -m comment --comment "DefaultAllow isolation for namespace: kube-public" -j ACCEPT
-A WEAVE-NPC-DEFAULT -m set --match-set weave-?b%zl9GIe0AET1(QI^7NWe*fO dst -m comment --comment "DefaultAllow isolation for namespace: kube-system" -j ACCEPT
COMMIT
# Completed on Thu Jul  5 13:24:35 2018
```

**Comment by thomaschaaf** [comment] 2018-07-05 13:35
@justinsb are you seeing similar problems on your clusters or does this never occur?

**Comment by Quentin-M** [comment] 2018-07-05 22:46
@thomaschaaf If the problem is indeed the race condition (it is very easy to understand if it is, by observing the insert_failed in conntrack), then my fix will definitely work as long as the configured target DNS port (in my case, 5353) is set properly. If your cloud provider and overlay is not respectively AWS / Weave (or if the network environment in general is not a complete match), the latency may have to be adjusted a little. If the target port is not set properly, the AAAA packets won't match the rule in the fix and it therefore won't work. If the issue you are seeing is not the kernel race condition, this has no effect.

**Comment by merlineus** [comment] 2018-07-16 18:32
I've just noticed same issues with dns resolving. Suggested fix by adding 'options single-request-reopen' to resolv.conf also doesn't help.

Host: Debian GNU/Linux 9 (stretch) 4.9.0-6-amd64
Image: Ubuntu 16.04
kube 1.9.3 via kops 1.9.1 with awsvpc network

**Comment by YoniTapingo** [comment] 2018-07-19 09:48
@Quentin-M Thanks for all the help.
"as long as the configured target DNS port (in my case, 5353) is set properly"
how can i check what port im using? [I used kops 1.9.1 and kubernetes 1.9.8 and nodes are on a debian image]

**Comment by Quentin-M** [comment] 2018-07-19 17:18
@YoniTapingo By default, your DNS server will listen over port 53 - except you unprivileged it. The TC script contains an occurrence of port 5353 https://github.com/Quentin-M/weave-tc/blob/9ed2ccf7989de6792915df1ac55c8f53054504cb/weave-tc.sh#L38 that needs to be changed if yours listen over 53

**Comment by fturib** [comment] 2018-07-21 21:57
FYI - @chrisohaver, @rajansandeep

**Comment by renilthomas** [comment] 2018-10-10 07:44
@thomaschaaf how did you solve this issue?

**Closed** 2019-03-09 08:52 UTC
Labels: lifecycle/rotten

**Comment by alex88** [comment] 2019-04-07 15:55
Is it possible to reopen this? There's still no solution on this
