### ISSUE TITLE
NAT gateway not available in AWS sa-east-1b forces several TF fixes

### ISSUE THREAD

**Issue by fwynyk** [kubernetes/kops#1537] opened 2017-01-19 02:23 UTC
In sa-east-1, AWS gives us 3 zones (A, B and C), but in the "B" zone they don't have NAT Gateway, instances class 4 and some other services. So we are trying to bring up an HA Kubernetes cluster using Kops in the other 2 zones (A and C), and it's been really hard to deal with that.

It would be great to have the ability to:
- Choose only 2 zones for masters and nodes in a HA cluster (friends using us-west-1 would appreciate the idea too);
- If not possible, at least an option to choose an instance type per zone;
- Also, an option to choose number of NAT gateways with respective zones (as we have for nodes and masters)

If you change `--zones` and `--master-zones` options to accept just 2 zones each, you solve the problem.

Other things to consider as improvements (out of the subject, but they're also changes in terraform that I need to do):
- Raise disk space up to 60GB (prevents full disks in a several deployments scenario)
- Use newest K8s AMI available with most recent Kernel and Docker versions (TF output gives AMI from Oct 2016 when we already have a Dec 2016 AMI available)

As you can see in the file attached, I needed to change all these things to get my cluster up and running stable, with most recent upgrades.

This discussion was started today on #kops channel of K8s slack with participation of @chrislovecnm and @justinsb. I think @justinsb in already working in the solution, but both asked me to put this issue here, as other guys using us-west-1 (suffering from the same kind of situation) would like to follow this thread.

[1.5.0-alpha3-cluster.tf.txt](https://github.com/kubernetes/kops/files/715522/1.5.0-alpha3-cluster.tf.txt)

**Comment by chrislovecnm** [comment] 2017-01-24 00:05
This is a duplicate of an issue to reduce the number of NAT gateways. Mind we would need to specify where we put the NGW.

**Comment by fwynyk** [comment] 2017-01-24 18:47
@chrislovecnm, what about the option to choose only 2 zones for masters and nodes?

**Comment by justinsb** [comment] 2017-01-25 05:14
We'll be able to run all the master instances in the same AZ in alpha5 (tonight / tomorrow), and the same should apply to two AZs (or three, of course!)  The issue for more efficient use of nat gateways is https://github.com/kubernetes/kops/issues/1368 ; we have support for sharing NAT gateways in alpha4, but we will still require one per zone.  But I don't think that is a concern if you only have two zones and want HA!

On some of the other points, I think we've already got them (if not, let me know / open issues):

> Raise disk space up to 60GB (prevents full disks in a several deployments scenario)

rootVolumeSize: https://github.com/kubernetes/kops/blob/master/docs/instance_groups.md#changing-the-root-volume-size-or-type

> Use newest K8s AMI available with most recent Kernel and Docker versions (TF output gives AMI from Oct 2016 when we already have a Dec 2016 AMI available)

Use `--channel alpha` and you'll get it.  The stable channel still has the 1.4 image (different versions of docker).  We'll probably need to update both images soon, probably around kops 1.5.0 release time.

> If not possible, at least an option to choose an instance type per zone;

You can choose an instance type per instance group, and kops puts masters in each AZ into different

**Comment by justinsb** [comment] 2017-02-05 21:29
So I think we have this covered now: `--master-count` makes it easy to run more masters than zones, #1368 is the only missing piece if you did want to run in sa-east-1b.

As such I am going to close (we'll track a shared NAT gateway in #1368), but if there's something I missed here please open a new issue or comment here.

**Closed by justinsb** 2017-02-05 21:29 UTC
