### ISSUE TITLE
Support spotFleet for instances groups

### ISSUE THREAD

**Issue by ese** [kubernetes/kops#1784] opened 2017-02-04 10:58 UTC
Spot fleets allow to use a wide range of instances types to provide certain amount of resources by requesting spot instances. This is great to provide capacity for workloads that require high amount of resources, dont require real-time interaction and are able to recover if the node dissapear
https://github.com/kubernetes/kubernetes/issues/24472
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html

**Comment by justinsb** [comment] 2017-02-05 15:59
I agree this would be a great feature.  There were some limitations around tagging of instances previously which make this non-trivial.  An interesting option (IMO) is to have the autoscaler be "spot fleet" aware; either by directly using spot fleet or by reimplementing spot fleet.

The advantage of reimplementing spot fleet is maybe the autoscaler can know better what resources are required, for example whether we need CPU or Memory or GPUs etc.  Also that it would be cloud agnostic.

**Comment by jpcope** [comment] 2017-05-11 01:49
The user mumoshu in the public kubernetes-incubator/kube-aws project has created an implementation that works around the tagging limitations https://github.com/kubernetes-incubator/kube-aws/blob/master/Documentation/kubernetes-on-aws-node-pool.md#deploying-a-node-pool-powered-by-spot-fleet

As an individual interested in running kubernetes in a production context, the target-capacity limitation of cloudformation with the aforementioned implementation documented at https://github.com/kubernetes-incubator/kube-aws/blob/master/Documentation/kubernetes-on-aws-node-pool.md#known-limitations is troubling.

> Running kube-aws update to increase or decrease targetCapacity of a spot fleet results in a complete replacement of the Spot Fleet hence some downtime. This is due to how CloudFormation works for updating a Spot Fleet

I do believe that a re-implementation of spot fleet would be beneficial especially if it means I can mix lifecycle type nodes and define pods that are `mission-critical` ( never use spot ) vs `highly-available` ( always have at least X pods on non-spot nodes; scale out using spot ) and `interruption-tolerant` ( only use spot )

In a production context zone coverage of application pods is also important. Ideally this should be adjustable so you can get the biggest bang for your buck if you are not running in production.

Also draining the pods when a termination is signaled http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#spot-instance-termination-notices will make a more opaque end-user experience of services running in the cluster.

**Comment by bcorijn** [comment] 2017-08-02 08:07
As mentioned in https://github.com/kubernetes/kubernetes/issues/24472, AWS now supports propagating tags on Spot Fleets!

**Comment by Globegitter** [comment] 2017-08-31 09:37
Would this then also allow to support https://github.com/cristim/autospotting? Or would it just be a matter of that tool to then have to set the right tag on each instance it attaches to the autoscaling group?

**Comment by ajohnstone** [comment] 2017-10-28 12:24
Any update on this ?
https://aws.amazon.com/about-aws/whats-new/2017/07/tag-your-spot-fleet-ec2-instances/

**Comment by justinsb** [comment] 2017-11-18 22:16
So spot fleet actually works with kubernetes, now that we have tagging support.  Changing a spot fleet configuration though is different from how ASGs work, so we need another approach.

I'm hoping we can look at this in the 1.9 1.10 timeframe, using the machines API probably.

**Comment by cdenneen** [comment] 2018-02-17 00:10
/remove-lifecycle-stale

@justinsb is there any updated docs on how to configure kops to do this?

**Comment by chrislovecnm** [comment] 2018-02-17 20:43
@cdenneen this needs to be implemented, we only support spot instances via the ASG API calls.

/lifecycle frozen
/remove-lifecycle stale

**Comment by chrislovecnm** [comment] 2018-02-17 20:44
I am marking with help wanted label since this is a bit of a project, not a great place to start, but a great feature to add.

**Comment by ese** [comment] 2018-03-27 08:16
I think this should be fixed in 1.10 https://github.com/kubernetes/kubernetes/pull/60125 if anyone can test it

**Comment by cjbottaro** [comment] 2018-08-08 14:39
Is there any documentation on how to manually make your own instance groups?

In EKS, I made my own spot fleet, but that is because the userdata for nodes joining an EKS cluster is pretty simple and I could easily change it up for my needs.

The userdata for nodes launched with kops is a bit more involved... :/

**Comment by cdenneen** [comment] 2018-08-08 14:54
@cjbottaro how did you make your own spot fleet for EKS? I'm interested in how you implemented this and the benefits you see in doing so. Thanks

**Comment by cjbottaro** [comment] 2018-08-08 15:50
**the benefits**

We currently run in ECS and we have two AGS (using launch configs) populating our cluster: one for on-demand instances and one for spot. More than a few times, we've seen spot prices spike, and thus wipe out 3/4 of our cluster, causing an outage before we realize what's going on and up our on-demand instances to take over.

Spot fleets (which require launch templates instead of launch configs) let you specify multiple machine types. So if prices spike for one type and get wiped out, the fleet will automatically fulfill other machine types that you can afford. Furthermore, you can tell the spot fleet to diversity among the machine types / availability zones, so there is less chance of max extinction.

**How in EKS**

I followed the tutorial to get an EKS cluster up and running, which includes creating a launch config and ASG for nodes. I simply converted the launch config to a launch template (by hand in the AWS web console) and copy/pasted the userdata which configures and starts kubelet, then made a spot fleet using that launch template. The [user data for EKS nodes](https://gist.github.com/cjbottaro/2f31f52c6cea1ab32c53e85d3a8b0c15) is pretty small and easy to understand. To add taints and labels, you can simply add something like this to the end of the user data:
```
NODE_NAME=`hostname -s`.ec2.internal
export KUBECONFIG=/var/lib/kubelet/kubeconfig
until kubectl get node $NODE_NAME; do sleep 1; done
kubectl label node $NODE_NAME lifecycle=od
kubectl taint node $NODE_NAME dedicated=datastores:NoExecute
```

**Issue with kops**

Kops has these first class objects `instancegroups` and it seems like the userdata for nodes is the output of a template plus the instancegroup manifest. The problem is that it _seems_ like there are _a lot_ of values in the manifest that come out in the user data... too many for a simple copy/paste of the resulting user data to not be error prone.

It would be nice if there was a command to output the user data for a given instancegroup:
```
kops export userdata my_instance_group
```
So we can create our own launch configs / launch templates.

Thanks!

**Comment by rbtcollins** [comment] 2018-10-28 22:12
I think this also needs some proper k8s core integration - I've filed https://github.com/kubernetes/kubernetes/issues/70342 about that.

**Comment by gambol99** [comment] 2018-12-31 18:34
related #6277

**Comment by disha1104** [comment] 2019-01-17 12:44
@gambol99 , I checked the PR, it looks great.
Does it mean, we'll be able to use launch templates and smart ASG's with Kops? As Kops currently only supports Launch Configuration.

**Comment by gambol99** [comment] 2019-01-17 13:41
@disha1104  ... 

> Does it mean, we'll be able to use launch templates and smart ASG's with Kops? 

yep :-) ..

**Comment by disha1104** [comment] 2019-01-17 13:47
That's really great.
Is this planned for next-release, like by when can I expect this feature?
Also, is the launch-configuration conversion to launch-template handled? And also the Spot-termination handler thing, like in terms of reliability of the nodes?

**Comment by oded-dd** [comment] 2019-02-11 11:33
It's amazing. I was thinking on using `spotinst` but once it is deployed I would rather use it.

When it is planned to be merged?

**Comment by gambol99** [comment] 2019-02-11 14:05
@disha1104 

> Is this planned for next-release, like by when can I expect this feature?

So I don't cut the releases ... you'd need to be speak to @justinsb

> Also, is the launch-configuration conversion to launch-template handled? 

The launch-configuration -> launch-template is done automatically _(though admittedly it leaves the LC hanging, so just needs to deleted manually post update)_  

> And also the Spot-termination handler thing, like in terms of reliability of the nodes?

So I this doesn't add a spot termination handler addon as I'd rather let the users choose how they want it done.

**Comment by disha1104** [comment] 2019-02-20 09:29
@justinsb which release is this planned for?

**Comment by wanghanlin** [comment] 2019-02-25 04:37
#6277 is merged, I think we can close this one :tada:
/close

**Closed** 2019-08-11 07:17 UTC
Labels: help wanted, lifecycle/rotten
