### ISSUE TITLE
Lots of DNS Pods created by default

### ISSUE THREAD

**Issue by tcf909** [kubernetes/kops#1334] opened 2017-01-03 22:46 UTC
I just finished setting up a new cluster in AWS with kops and noticed an extreme amount of pods launched by default for DNS:

I'm running a 3 x masters with PreferNoSchedule (rather than NoSchedule) taints. I'm not really sure why so many dns-controllers and kube-dns pods are trying to be launched?

Any guidance would be appreciated.

NAMESPACE     NAME                                                                  READY     STATUS             RESTARTS   AGE
default       busybox                                                               1/1       Running            0          5m
kube-system   dns-controller-1062112118-06t7s                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-0rupg                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-0uqe6                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-0y99e                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-1b5i4                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-1fop9                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-1h4zi                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-1mitm                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-22vxk                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-2a8w7                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-2i1ml                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-3ucbc                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-3v8du                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-5w5rp                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-61czt                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-650m0                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-7119m                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-7oiwc                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-9rfrt                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-9xsrj                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-a35f8                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-a3yk4                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-a9zy9                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-aasma                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-bc2pf                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-bed51                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-bg9hv                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-ctpg6                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-d04gn                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-d86ps                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-ddrt2                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-e0gco                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-enrnc                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-eq26h                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-f6v1b                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-g6nfm                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-gf7ch                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-ggkm3                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-gqvbi                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-gujc7                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-ie47z                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-j1e0y                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-jr2ni                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-l2smm                                       1/1       Running            0          1m
kube-system   dns-controller-1062112118-ldftk                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-lljxt                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-mas6z                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-mh3hg                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-mlz4z                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-n0bcq                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-nuth5                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-o9ben                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-ojwns                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-oxeub                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-p93fe                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-potfp                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-ptulo                                       0/1       OutOfcpu           0          2m
kube-system   dns-controller-1062112118-qqqc9                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-r94w6                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-t6363                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-u24m5                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-uvvgy                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-v642j                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-wbi1m                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-werqe                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-x4l4p                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-xv2x4                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-yg53v                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-yw6jo                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-z5qxd                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-zcuwr                                       0/1       OutOfcpu           0          1m
kube-system   dns-controller-1062112118-zhbml                                       0/1       OutOfcpu           0          1m
kube-system   etcd-server-events-ip-172-20-115-54.us-west-2.compute.internal        1/1       Running            0          1m
kube-system   etcd-server-events-ip-172-20-84-62.us-west-2.compute.internal         1/1       Running            0          8m
kube-system   etcd-server-ip-172-20-115-54.us-west-2.compute.internal               1/1       Running            0          1m
kube-system   etcd-server-ip-172-20-84-62.us-west-2.compute.internal                1/1       Running            0          8m
kube-system   kube-apiserver-ip-172-20-115-54.us-west-2.compute.internal            1/1       Running            4          2m
kube-system   kube-apiserver-ip-172-20-51-45.us-west-2.compute.internal             1/1       Running            3          1m
kube-system   kube-apiserver-ip-172-20-84-62.us-west-2.compute.internal             1/1       Running            2          9m
kube-system   kube-controller-manager-ip-172-20-115-54.us-west-2.compute.internal   1/1       Running            0          1m
kube-system   kube-controller-manager-ip-172-20-51-45.us-west-2.compute.internal    1/1       Running            0          27s
kube-system   kube-controller-manager-ip-172-20-84-62.us-west-2.compute.internal    1/1       Running            1          9m
kube-system   kube-dns-782804071-0dtz8                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-1ltb0                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-483yi                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-5kic4                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-870d9                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-8ahi4                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-9i2gu                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-ae5kj                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-c0ecs                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-d2zl8                                              0/4       OutOfcpu           0          2h
kube-system   kube-dns-782804071-fcy2h                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-gxyj4                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-j26ii                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-ox5wg                                              0/4       Pending            0          2m
kube-system   kube-dns-782804071-qx596                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-rhsrn                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-thtzp                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-xyk30                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-782804071-y4ae5                                              0/4       OutOfcpu           0          2m
kube-system   kube-dns-autoscaler-2715466192-tg7n6                                  0/1       Pending            0          2m
kube-system   kube-proxy-ip-172-20-115-54.us-west-2.compute.internal                1/1       Running            0          1m
kube-system   kube-proxy-ip-172-20-84-62.us-west-2.compute.internal                 1/1       Running            0          8m
kube-system   kube-scheduler-ip-172-20-115-54.us-west-2.compute.internal            1/1       Running            0          2m
kube-system   kube-scheduler-ip-172-20-51-45.us-west-2.compute.internal             1/1       Running            0          12s
kube-system   kube-scheduler-ip-172-20-84-62.us-west-2.compute.internal             1/1       Running            0          9m
kube-system   kubernetes-dashboard-3095304083-fnx4g                                 0/1       CrashLoopBackOff   5          8m

**Comment by chrislovecnm** [comment] 2017-01-04 00:07
Can you give us more detail?

Kops version
Steps used to reproduce

This is not the expected behavior.

**Comment by tcf909** [comment] 2017-01-04 18:12
Version git-f7a7d4c [HEAD]

I ran the node pool at minimum 0, desired 0, max 3 and the master pool at minimum 3, desired 3, max 3 (both node and max setup across 3 availability zones).

(So only 3 masters were running using T2.Micro instances).

I then adjusted the taint to be dedicated=master:PreferNoSchedule.

I added the UI using latest github README instructions.

I ran a busybox container.

kops rolling-update --force --yes was used 3+ times.

That got me to the problem. 

(My goal was to just use master nodes at idle and scale the node pool as needed. The seemed to work to launch busy box instances, etc.)

Ultimately, to resolve the issue and get DNS online, I needed to:

Modify the taint to: -dedicated (not just PreferNoSchedule)
Delete all zombie pods with Pending / OutOfcpu

**Comment by ctolon22** [comment] 2017-02-17 10:29
Hi, have you find the reason of this issue? I'm having the same problem right now...

TY

**Comment by tcf909** [comment] 2017-02-17 23:20
I figured out that there were a bunch of replica sets not being cleaned up
by the deployment object. I never figured out why the replica sets were
never cleaned up, but now running 1.5 and cleaning up the replica sets
manually resolved the issue for me so far.

**Comment by chrislovecnm** [comment] 2017-11-05 04:43
Closing ... please use prow to repoen if needed

**Closed by chrislovecnm** 2017-11-05 04:43 UTC
