### ISSUE TITLE
KUBE_ENABLE_CLUSTER_AUTOSCALER using kops on AWS?

### ISSUE THREAD

**Issue by mohanbmahajan** [kubernetes/kops#531] opened 2016-09-28 12:46 UTC
As per [autoscaling with kubenetes](http://blog.kubernetes.io/2016/07/autoscaling-in-kubernetes.html) we can enable k8s-cluster autoscaling using KUBE_ENABLE_CLUSTER_AUTOSCALER=true while running kube-up.sh. And I guess [k8s AWS Autoscaling](https://github.com/kubernetes/kubernetes/issues/11935) is available with v1.4.0 for AWS as well.
So, can you point me to documentation for how to enable autoscaling while setting up k8s-cluster using kops?

**Comment by mohanbmahajan** [comment] 2016-10-03 09:55
can I achieve above using kops?

**Comment by yissachar** [comment] 2016-11-16 18:59
Dupe of https://github.com/kubernetes/kops/issues/341

**Comment by chrislovecnm** [comment] 2016-11-17 07:21
Closing because of dude

**Closed by chrislovecnm** 2016-11-17 07:21 UTC
