### ISSUE TITLE
Unable to update cluster from 1.21 -> 1.22, kops controller crashlooping in AWS

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kops#12249] opened 2021-09-02 06:26 UTC
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.22 beta 1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.22.1

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I am updating cluster from 1.21.x k8s (it was installed by using kops 1.21) to 1.22.1 (using kops 1.22 beta 1)

**5. What happened after the commands executed?**

I see kops-controller in new 1.22.1 master crashlooping

```
kops-controller-fzdhz                                                    0/1     CrashLoopBackOff   8 (4m33s ago)   20m   10.124.44.193     ip-10-124-44-193.eu-central-1.compute.internal    <none>           <none>
```

```
% kubectl logs kops-controller-fzdhz
E0902 06:26:05.813281       1 deleg.go:144] setup "msg"="unable to start server" "error"="reading \"kubernetes-ca\" certificate: open /etc/kubernetes/kops-controller/pki/kubernetes-ca.pem: no such file or directory"
```

**6. What did you expect to happen?**
-

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by olemarkus** [comment] 2021-09-02 06:34
/cc @johngmyers 

If I understand things correctly, `kops update` should fix the file path for the new master.

**Comment by zetaab** [comment] 2021-09-03 10:43
its impossible currently to update old clusters, all masters are failing

**Comment by zetaab** [comment] 2021-09-05 13:07
I recreated the cluster but now it somehow works?

```
root@ip-10-124-48-35:/etc/kubernetes/kops-controller# ls -l
total 20
-rw------- 1 kops-controller root  410 Sep  5 13:00 keypair-ids.yaml
-rw-r--r-- 1 kops-controller root 1204 Sep  5 13:00 kops-controller.crt
-rw------- 1 kops-controller root 1679 Sep  5 13:00 kops-controller.key
-rw------- 1 kops-controller root 1082 Sep  5 13:00 kubernetes-ca.crt
-rw------- 1 kops-controller root 1679 Sep  5 13:00 kubernetes-ca.key
```

there is no .pem file that it tried to search

**Comment by zetaab** [comment] 2021-09-05 14:29
I cannot reproduce this anymore, lets reopen if needed

**Comment by zetaab** [comment] 2021-09-05 17:14
this is valid problem, it will happen in 20-50% of clusters

**Comment by zetaab** [comment] 2021-09-15 11:42
We have now updated quite many clusters, this problem is not present in OpenStack. But it do exists in all AWS clusters, always the first rolling update will fail to this problem.

**Comment by olemarkus** [comment] 2021-09-21 19:43
I am a bit in "don't understand how this can happen, but it happens" mode. Seems related to https://github.com/kubernetes/kops/issues/12299#issuecomment-924040060

**Comment by olemarkus** [comment] 2021-09-23 06:45
So after quite a lot of digging, this happens because we removed version from addons.

1.21 channels will check if a version is set, if it is not, it will skip the update!

That means that a `kops update` from 1.22 will not be applied until _after_ the first master rolls. This leads to a number of addons breaking, but especially kops-controller and other onDelete DaemonSets. It also delays fixing the upgrade test as the dns-controller change need to be applied _before_ the master is rolled.

A couple of ways to go about this:

Add the Version field to addons again, but set it to a fixed, high version (e.g 99.99.99) to all addons. This is most likely the simplest fix.

Bundle channels into the kops binary and let `kops update` also do a channels run (if the API is available). This is a larger change, but also has some benefits: channel updates are applied immediately after kops update, and a lot more information about addons is made more easily available to users. This also resolves the common support question of "how do I trigger a reinstall of an addon".

/kind office-hours

**Comment by hakman** [comment] 2021-09-23 08:28
> Add the Version field to addons again, but set it to a fixed, high version (e.g 99.99.99) to all addons. This is most likely the simplest fix.

@olemarkus Can we hardcode the version string in the manifest(s) only?

**Comment by olemarkus** [comment] 2021-09-23 08:34
Yeah. That was my idea. Set the version unconditionally before we encode the yaml.

**Comment by hakman** [comment] 2021-09-23 08:48
Meant in the `upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template` for example, not in code.

**Comment by olemarkus** [comment] 2021-09-23 08:56
What we need to ensure is that the following condition does not happen: https://github.com/kubernetes/kops/blob/release-1.21/channels/pkg/channels/channel_version.go#L110-L113

As far as I know, the manifests themselves are not related to this.

**Comment by rifelpet** [comment] 2021-09-23 12:46
This also breaks dns-controller (a Deployment with 1 replica) which breaks our upgrade tests:
* dns-controller used to tolerate all taints, this was fixed in https://github.com/kubernetes/kops/pull/12389 which will be in kops 1.23
* During a `kops rolling-update cluster` when the single-control-plane instance is cordoned and drained prior to termination, the dns-controller pod gets rescheduled onto it after draining because it can tolerate the cordon taint. Kops then deletes the node object and terminates the instance.
* With a non-static, non-daemonset pod scheduled on the node being deleted, KCM's PodGC controller on the new instance gets confused and is unable to delete the old dns-controller pod, preventing a replacement dns-controller pod from ever being scheduled. This means the API DNS record never get updated to point to new control plane instance, and cluster validation inevitably fails.

We have the fix in kops 1.23 but because of this bug, the manifest wont be applied by the old control plane instance, only the new instance after the pod that can't be garbage collected which breaks the rolling update.


[KCM Logs showing PodGC issues](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-k121-ko121-to-klatest-kolatest/1440387880051544064/artifacts/52.194.231.37/kube-controller-manager.log). These lines are repeated every 40 seconds:

`I0921 19:08:00.574823       1 gc_controller.go:182] Found orphaned Pod kube-system/dns-controller-56b8dc9b5b-sb7wv assigned to the Node ip-172-20-36-55.ap-northeast-1.compute.internal. Deleting.
I0921 19:08:00.574847       1 gc_controller.go:78] PodGC is force deleting Pod: kube-system/dns-controller-56b8dc9b5b-sb7wv
E0921 19:08:00.576118       1 gc_controller.go:184] pods "dns-controller-56b8dc9b5b-sb7wv" not found`

This causes the replicaset operations by the deployment controller to fail, preventing the deployment's rolling update to progress which prevents the new dns-controller pod from being scheduled on the new control plane node:


`E0921 19:08:44.888767       1 deployment_controller.go:495] Operation cannot be fulfilled on replicasets.apps "dns-controller-56b8dc9b5b": the object has been modified; please apply your changes to the latest version and try again
I0921 19:08:44.888986       1 deployment_controller.go:496] "Dropping deployment out of the queue" deployment="kube-system/dns-controller" err="Operation cannot be fulfilled on replicasets.apps \"dns-controller-56b8dc9b5b\": the object has been modified; please apply your changes to the latest version and try again"`

**Closed** 2021-09-30 19:21 UTC
Labels: kind/bug, priority/important-soon, kind/office-hours

**Comment by naeri-kailash** [comment] 2022-06-14 00:52
I'm not sure this is the best approach but my solution was:
 1. ssh into the new master node with the working `kops-controller` pods running in it and move into `/etc/kubernetes/kops-controller` which will have the following files 
  ```
  keypair-ids.yaml
  kubernetes-ca.key
  kubernetes-ca.crt
  ```
2. ssh into both of the old master nodes and navigate to `/etc/kubernetes/kops-controller`. Copy the files from the master node in step one into this folder
3. restart the errored `kops-controller` pods - and it started working again

**Comment by xgt001** [comment] 2022-09-22 16:12
Hi we ran into this upgrading from 1.21.10 to 1.22.13 on AWS with kops version 1.22.6
I believe the issue is with the add-on being updated in the S3 store but not being applied. 
The sequence of events:
1. The first new master comes up, looks for an updated addon config with the signingCA `kubernetes-ca` in `/etc/kubernetes/kops-controller/` only to not find it and enter into a crash loop
2. Update this by downloading the addon file from AWS s3 in a path that should be similar to this 
` aws s3 cp s3://cluster-bucket-name/cluster-name/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml .`
3. Apply the addon so that the new master can pick up the right path 
4. This is where we got stumped, the cluster validation failed because one of the older kops-controller pods on the older nodes started crash looping because they some how read this updated 1.22's yaml configuration (!!!)
5. Luckily we had versioning enabled on our S3 Bucket and we could feed the older `kops-controller` the add on config from the same bucket for the older version (from 1.21) 
6. For the rolling update with the next master, we had to apply the addon from 1.22 again. From this point on however, we didnt have to revert to 1.21's addons.yaml
