### ISSUE TITLE
kops does not clean up old launch configurations

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kops#4472] opened 2018-02-20 14:52 UTC
It appears that each time you change the configuration of an ig that requires a rolling-update, it creates a new launch configuration, but *does not get rid of older ones*.

Understandably it might be difficult to say "reuse the old version of this configuration" so maybe it might be easier to declare in the cluster config to drop any launch configurations older than a certain time period (for example 1month) or keep only a fixed number of launch configurations for an ig (e.g. keep only the last 10 configs)

Example:

![image](https://user-images.githubusercontent.com/2756283/36430318-d0b08c28-164c-11e8-9ce6-906c49701391.png)

**Comment by chrislovecnm** [comment] 2018-02-20 19:26
This is a known issue ;( Duplicafe bug. On mobile right now so not going to find it right now.

**Comment by mikesplain** [comment] 2018-02-20 19:42
Dupe of https://github.com/kubernetes/kops/issues/329

**Comment by mikesplain** [comment] 2018-02-20 19:45
@huang-jy I'm going to close this. If you feel this is a different issue then linked above, please reopen :).

/close

**Closed by mikesplain** 2018-02-20 19:46 UTC

**Comment by huang-jy** [comment] 2018-02-20 20:25
It's cool, thanks, @mikesplain I didn't realise there was already an issue open for this ^^
