### ISSUE TITLE
Are we sometimes leaking elastic ips?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kops#1431] opened 2017-01-10 16:42 UTC
Because we can't tag elastic IPs, we have a much bigger window where we can leak an elastic IP.

Splitting out from #1427, which had a few simple leaks of IAM & Route53 resources, because this is a much more complex only-if-things-go-wrong leak (I think!)

cc @AlexLast

**Comment by AlexLast** [comment] 2017-01-10 21:22
@justinsb I think you're right in saying it's when stack spin up fails, I haven't seem them left around that often.

**Comment by geojaz** [comment] 2017-01-10 23:24
I am pretty sure we leak EIPs intermittently, although in my experience, it doesn't happen super frequently.. but I would say, I've had my suspicions- but assumed they were me, not kops O:) Next time I see something 'spicious, I will make sure to update this with details. 

I think the idea that these may get left behind during failed spin-up seems quite probable.

**Comment by ahawkins** [comment] 2017-01-18 05:34
@justinsb I can confirm we've seen leaks on 1.4 and 1.5.0-alpha3.

**Comment by chrislovecnm** [comment] 2017-01-18 22:36
@justinsb / @ahawkins can we close?

**Comment by ahawkins** [comment] 2017-01-19 02:15
Seems to be fixed on 1.5.0-alpha3. This issue should go as a resolved
bug in the changelog :)




On Thu, Jan 19, 2017, at 04:06 AM, Chris Love wrote:

> @justinsb[1] / @ahawkins[2] can we close?



> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].
> 




Links:

  1. https://github.com/justinsb
  2. https://github.com/ahawkins
  3. https://github.com/kubernetes/kops/issues/1431#issuecomment-273624165

**Comment by kris-nova** [comment] 2017-01-19 22:22
Closing - thanks everyone!

**Comment by justinsb** [comment] 2017-01-24 16:37
Reopening ... we do have a fairly big window of loss right now where we can still leak the EIP (I think), during creation of the NAT gateway.

**Comment by chrislovecnm** [comment] 2017-01-24 16:50
@zmerlynn do you have a report of hanging chaff that the janitor script picks up?

**Comment by justinsb** [comment] 2017-01-29 06:07
Going to move to 1.5.1, will be addressed as part of tagging work I believe.

**Comment by chrislovecnm** [comment] 2017-01-29 06:11
@justinsb I have not seen this ...

**Comment by geojaz** [comment] 2017-01-29 06:13
I have seen this but I can't confirm that they leak with latest version. I
think we should leave open to allow for us to rule it out beyond reasonable
doubt....

**Comment by geojaz** [comment] 2017-01-29 06:14
I think pushing to 1.5.1 for definitive answer is very appropriate.

**Comment by ikropotov** [comment] 2017-02-10 13:22
I've found a bug related to the elastic IPs leaking on cluster deletion. While setting a cluster I had to delete it on 1.5 version and got a bunch of elastic-ips that are not related to the cluster and actually it's production so I scared for not a bit(hopefully AWS didn't allow to erase elastic-ips that are used), so taking a glance at the source I've found that the list of associated elastic-ips is fetched here:
https://github.com/kubernetes/kops/blob/master/upup/pkg/kutil/delete_cluster.go#L756
You can see that it checks if any other EC2 ips are within it:
https://github.com/kubernetes/kops/blob/master/upup/pkg/kutil/delete_cluster.go#L779

but the flag should be inversed (if associated ips doesn't include the ec2 ip, then skip it)
if elasticIPs.Has(ip) -> if !elasticIPs.Has(ip)

as it has been before refactoring in this commit:
https://github.com/kubernetes/kops/commit/3d10e8a048a0ca57c02eb4ece42979da5ee91a1d#diff-944da2e6a328fdeef239da66af6346cbL908

**Comment by chrislovecnm** [comment] 2017-02-14 04:03
@ikropotov can we close this?

**Comment by ikropotov** [comment] 2017-02-14 08:38
I would suggest that fist @justinsb test it, as he reopened it with the case on creating NAT gateway

**Comment by geojaz** [comment] 2017-09-09 19:51
closing via #1844

**Closed by geojaz** 2017-09-09 19:51 UTC
Labels: chunk/tags

**Comment by rahulakash** [comment] 2018-07-06 20:23
All, 
 
This issue seems to have re-surfaced in 1.9.0.

We see this below error when deleting a cluster.

`elastic-ip:eipalloc-ae441b92	error deleting resources, will retry: error deleting elastic ip "35.161.93.54": AuthFailure: You do not have permission to access the specified resource.`

Any help is highly appreciated.
