### ISSUE TITLE
Creating subnets fail with InvalidSubnet.Range error on /24 network CIDR

### ISSUE THREAD

**Issue by khos2ow** [kubernetes/kops#9129] opened 2020-05-14 23:13 UTC
This is pretty much identical duplicate of #7193. I opened this for visibility, feel free to close this one in favor of the other.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

- `1.16.2 (git-f5093e414)`
- `1.17.0-beta.2 (git-e0d2809d0)`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

`default version in channel`

**3. What cloud provider are you using?**

`aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster \
    --cloud aws\
    --authorization rbac \
    --topology private \
    --network-cidr 172.19.1.0/24 \
    --networking canal \
    --bastion\
    --node-count 3 \
    --node-size t2.large \
    --zones us-east-1a,us-east-1b,us-east-1c \
    --master-count 1 \
    --master-size c4.large \
    --ssh-public-key ~/.ssh/key.pub \
    --state s3://kops-state \
    k8s.example.com
```

then:

- `kops edit cluster ...` and changed `spec.api.loadBalancer.type` to `Internal`
- `kops update cluster ... --yes`

My main objective is to spin up VPC with provided network CIDR i.e `172.19.1.0/24` (this cidr is a hard requirement).

**5. What happened after the commands executed?**

```
error running task "Subnet/utility-us-east-1b.k8s.example.com" (9m25s remaining to succeed): error creating subnet: InvalidSubnet.Range: The CIDR '172.19.1.4/30' is invalid.
        status code: 400, request id: uuid-2
error running task "Subnet/utility-us-east-1a.k8s.example.com" (9m25s remaining to succeed): error creating subnet: InvalidSubnet.Range: The CIDR '172.19.1.0/30' is invalid.
        status code: 400, request id: uuid-1
error running task "Subnet/utility-us-east-1c.k8s.example.com" (9m25s remaining to succeed): error creating subnet: InvalidSubnet.Range: The CIDR '172.19.1.8/30' is invalid.
        status code: 400, request id: uuid-3
```

**6. What did you expect to happen?**

If I run the exact same setup above only with `/22` everything will work, but not with `/24`. In other words with `/24` it tries to create two sets of subnets: 1) `/27` and 2) `/30`. and only `/30` for utility fails to get created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

<details><summary><code>kops.yaml</code> Content</summary><br><pre>
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-05-14T22:56:36Z"
  generation: 1
  name: k8s.example.com
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state/k8s.example.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.5
  masterInternalName: api.internal.k8s.example.com
  masterPublicName: api.k8s.example.com
  networkCIDR: 172.19.1.0/24
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.19.1.32/27
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 172.19.1.64/27
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 172.19.1.96/27
    name: us-east-1c
    type: Private
    zone: us-east-1c
  - cidr: 172.19.1.0/30
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - cidr: 172.19.1.4/30
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - cidr: 172.19.1.8/30
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    bastion:
      bastionPublicName: bastion.k8s.example.com
    dns:
      type: Public
    masters: private
    nodes: private
</pre>
<pre>
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-14T22:56:36Z"
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: bastions
spec:
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-1a
  - utility-us-east-1b
  - utility-us-east-1c
</pre>
<pre>
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-14T22:56:36Z"
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: master-us-east-1a
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a
</pre>
<pre>
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-05-14T22:56:36Z"
  labels:
    kops.k8s.io/cluster: k8s.example.com
  name: nodes
spec:
  associatePublicIp: false
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
</pre></details>

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

**Comment by khos2ow** [comment] 2020-05-15 18:40
Based on [this message](https://kubernetes.slack.com/archives/C3QUFP0QM/p1517908874000553) in slack which led me to the AWS doc, the minimum allowed subnet size is `/28`. With manually editing the cluster config's subnet and change /30 subnets to /28 and adjust /27s with the new change I was able to make it work.

So it might worth to consider https://github.com/kubernetes/kops/issues/7193#issuecomment-506635411 and calculate subnets slightly differently when provided `--network-cider` is `/24`.

I'm gonna leave this issue open for visibility and for the maintainers to decide to close it or not.

**Comment by olemarkus** [comment] 2020-05-21 18:05
I'll close this one as dupe of #7193 
I'll see if there is anything to do about the logic.

/close

**Closed** 2020-05-21 18:05 UTC
