### ISSUE TITLE
Request to allow custom code to be added to the IG launch config userdata

### ISSUE THREAD

**Issue by hsteckylf** [kubernetes/kops#2230] opened 2017-03-29 14:13 UTC
There are certain scripts we would like to be able to add to the userdata of the kops generated launch configs. Being able to add those to a parameter in the `kops edit ig` configs and having that appended to the generated userdata would be greatly appreciated.

**Comment by yissachar** [comment] 2017-03-29 16:58
Closing this as a duplicate of #387. If you think this is an error, please re-open with a comment!

**Closed by yissachar** 2017-03-29 16:58 UTC
