### ISSUE TITLE
 AssumeRoleTokenProviderNotSetError MFA not working for 1.9

### ISSUE THREAD

**Issue by rudymccomb** [kubernetes/kops#4972] opened 2018-04-11 22:31 UTC
1. What versoin of Kops
 kops version 1.9.0

2. What version of Kubernetes
Kubernetes 1.10.0

3. What cloud provider
AWS 

4. What command did I run
 I ran `kops upgrade cluster --state s3://node.tld --name kubecluster

5. What happened after the commands executed?
Using cluster from kubectl context: kubecluster

error reading cluster configuration: error reading cluster configuration "kubecluster": error reading s3://node.tld/kubecluster/config: error connecting to S3: error starting new AWS session: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.

6. What did you expect to happen?
For my cluster to be upgraded 

9. Anything else do we need to know?
I'm unable to post my manifest but this issue can be duplicated

------------- FEATURE REQUEST TEMPLATE --------------------

1. Describe IN DETAIL the feature/behavior/change you would like to see.
I would like MFA to work with kops 1.9 currently it does not

**Comment by jeyglk** [comment] 2018-04-13 09:10
Same issue here:

```
error reading state store: error connecting to S3: error starting new AWS session: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
```

We should be able to input the MFA.

**Comment by jeyglk** [comment] 2018-04-13 09:17
Actually this is a duplicate of https://github.com/kubernetes/kops/issues/226

**Comment by justinsb** [comment] 2018-09-10 16:45
/reopen

Likely a dup of #226, but I don't want to lose it until we close 226.

**Closed** 2018-10-10 17:45 UTC
Labels: lifecycle/rotten
