### ISSUE TITLE
Not allow to create IG separated from master nodes for etcd ?

### ISSUE THREAD

**Issue by jyyeom** [kubernetes/kops#9725] opened 2020-08-11 04:16 UTC
https://github.com/kubernetes/kops/blob/cdbb780534d4023ac7b47323d4a99c088e552903/pkg/apis/kops/validation/instancegroup.go#L198

I wanted to create cluster with separated IG for ETCD cluster with node role.

I wonder validation that force master nodes to have etcdCluster is necessary ?

**Comment by johngmyers** [comment] 2020-08-11 05:13
Duplicate of #772
/close

**Closed** 2020-08-11 05:13 UTC
