### ISSUE TITLE
KOPS has not supported yet in Jakarta region

### ISSUE THREAD

**Issue by ajizkai** [kubernetes/kops#13821] opened 2022-06-16 23:53 UTC
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

*Version 1.23.2 (git-4125bbbe975ca104c609ceaa625a9a5ff3ac19f4)*

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Unable to connect to the server: EOF
```

**3. What cloud provider are you using?**
*aws*

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

*just simple command for creating cluster*
```
kops create cluster --name=${CLUSTER_NAME} --vpc=${VPC_ID} --networking calico --node-count 2 --master-count 3 \
--master-size t3.small --node-size t3.small --discovery-store=s3://kuberentes-integration-oidc-store/${NAME}/discovery $NAME \
--cloud aws --zones ap-southeast-3a,ap-southeast-3b,ap-southeast-3c \
--master-zones ap-southeast-3a,ap-southeast-3b,ap-southeast-3c --ssh-public-key jump-id.pub
```

**5. What happened after the commands executed?**
*kubernetes finds the etcd cluster by port 4001, but etcd cluster running on port 3997/3996*

**6. What did you expect to happen?**
*I expecting that etcd must be running on port 4001 not 3996*

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-06-16T22:56:33Z"
  name: integration.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://xxx/integration.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-3a
      name: a
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-3b
      name: b
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-3c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-3a
      name: a
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-3b
      name: b
    - encryptedVolume: true
      instanceGroup: master-ap-southeast-3c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.23.7
  masterPublicName: api.integration.k8s.local
  networkCIDR: 10.244.0.0/16
  networkID: vpc-xxx
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://xxxe/integration.k8s.local/discovery/integration.k8s.local
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 10.244.32.0/19
    name: ap-southeast-3a
    type: Public
    zone: ap-southeast-3a
  - cidr: 10.244.64.0/19
    name: ap-southeast-3b
    type: Public
    zone: ap-southeast-3b
  - cidr: 10.244.96.0/19
    name: ap-southeast-3c
    type: Public
    zone: ap-southeast-3c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
***ETCD LOG*** *it's seems healthy cluster 😸*
```
I0616 23:41:30.822544    5397 controller.go:187] starting controller iteration
I0616 23:41:30.822645    5397 controller.go:212] we are not leader
I0616 23:41:33.439369    5397 leadership.go:37] Got LeaderNotification view:<leader:<id:"etcd-events-a" endpoints:"10.244.33.235:3997" > leadership_token:"TC7p8-_oAHO1TqSbGEB5KQ" healthy:<id:"etcd-events-a" endpoints:"10.244.33.235:3997" > healthy:<id:"etcd-events-b" endpoints:"10.244.79.110:3997" > healthy:<id:"etcd-events-c" endpoints:"10.244.116.89:3997" > >
I0616 23:41:40.823848    5397 controller.go:187] starting controller iteration
I0616 23:41:40.823888    5397 controller.go:212] we are not leader
I0616 23:41:43.445629    5397 leadership.go:37] Got LeaderNotification view:<leader:<id:"etcd-events-a" endpoints:"10.244.33.235:3997" > leadership_token:"ZthM3I7sVuAJx92DpCkOZA" healthy:<id:"etcd-events-a" endpoints:"10.244.33.235:3997" > healthy:<id:"etcd-events-b" endpoints:"10.244.79.110:3997" > healthy:<id:"etcd-events-c" endpoints:"10.244.116.89:3997" > >
```

***APISERVER LOG***
```
W0616 23:51:10.252666      11 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:4001 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4001: connect: connection refused". Reconnecting...
W0616 23:51:14.511187      11 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:4001 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4001: connect: connection refused". Reconnecting...
W0616 23:51:15.559130      11 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:4001 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4001: connect: connection refused". Reconnecting...
E0616 23:51:20.578459      11 run.go:74] "command failed" err="context deadline exceeded"
```

**9. Anything else do we need to know?**
*thank you!*

**Comment by hakman** [comment] 2022-06-17 03:40
Ports 3996 & 3997 are used for etcd-manager internal communication. My guess is that there's an error somewhere in etcd-manager logs.
https://kops.sigs.k8s.io/contributing/ports/
| Port | Description                              |
|------|------------------------------------------|
| 3994 | etcd-manager - main - quarantined        |
| 3995 | etcd-manager - events - quarantined      |
| 3996 | etcd-manager - main - grpc               |
| 3997 | etcd-manager - events - grpc             |
| 4001 | etcd main client                         |
| 4002 | etcd events client                       |

**Comment by ajizkai** [comment] 2022-06-17 03:52
Do you have any information about where directory ETCD configured in? 
So I can find error each directory

**Comment by hakman** [comment] 2022-06-17 04:08
etcd is configured by [etcd-manager](https://github.com/kubernetes-sigs/etcdadm/tree/master/etcd-manager), which is started as static pods from the manifests in `/etc/kubernetes/manifests/`:
```
ls -1 /etc/kubernetes/manifests/etcd-*
/etc/kubernetes/manifests/etcd-events.manifest
/etc/kubernetes/manifests/etcd-main.manifest
```

There are 2 etcd clusters,`main` and a separate one for `events`.
Each master node has 2 volumes attached, one for each etcd cluster. They are created by kOps and attached by etcd-manager. If etcd doesn't start, most likely the problem is in etcd-manager container logs that you could find in `/var/log/containers/`.

**Comment by ajizkai** [comment] 2022-06-17 04:26
Oh, I got the error, I think that my region has'nt supported yet with this kops version, my region is Jakarta

here is the error:
```
I0617 04:16:20.886155    5397 commands.go:41] refreshing commands
I0617 04:16:20.886317    5397 s3context.go:340] product_uuid is "ec2d165d-125f-1695-881f-0707f1715c7d", assuming running on EC2
I0617 04:16:20.887772    5397 s3context.go:169] got region from metadata: "ap-southeast-3"
W0617 04:16:20.887813    5397 controller.go:163] unexpected error running etcd cluster reconciliation loop: error refreshing control store after leadership change: error reading s3://integration-kubernetes/integration.k8s.local/backups/etcd/main/control: ap-southeast-3 is not a valid region
Please check that your region is formatted correctly (e.g. us-east-1)
```
What do you think @hakman?

**Comment by hakman** [comment] 2022-06-17 04:38
I think you are correct. It should be fixed in a future version, but you can try some other region in the mean time.

**Comment by ajizkai** [comment] 2022-06-17 04:42
I hope it fixed in soon,

Thank you @hakman

**Closed** 2022-06-18 09:16 UTC
Labels: kind/bug

**Comment by ajizkai** [comment] 2022-06-19 03:44
umm, sorry @hakman.

1 question, which version that fixed this problem?

**Comment by hakman** [comment] 2022-06-19 05:43
The fix will be in next 1.23 and 1.24 release of kOps. I would say 1-2 weeks away.

**Comment by hakman** [comment] 2022-06-20 06:03
You could also use the new etcd-manager image with your current version of kOps:
```bash
export KOPS_FEATURE_FLAGS=SpecOverrideFlag
kops edit cluster --set "spec.etcdClusters[*].manager.image=k8s.gcr.io/etcdadm/etcd-manager:v3.0.20220617"
kops update cluster
kops update cluster --yes
kops rolling-update cluster --instance-group-roles=Master
```

**Comment by ajizkai** [comment] 2022-06-20 07:25
It's work sir, and my kubernetes cluster it's now running.

Thank you for your support @hakman 

```
ubuntu@iac:~$ kubectl get nodes
NAME                                                STATUS   ROLES                  AGE     VERSION
ip-10-244-107-197.ap-southeast-3.compute.internal   Ready    control-plane,master   8m22s   v1.23.7
ip-10-244-49-236.ap-southeast-3.compute.internal    Ready    node                   7m13s   v1.23.7
ip-10-244-62-21.ap-southeast-3.compute.internal     Ready    control-plane,master   8m23s   v1.23.7
ip-10-244-79-39.ap-southeast-3.compute.internal     Ready    node                   7m11s   v1.23.7
ip-10-244-90-240.ap-southeast-3.compute.internal    Ready    control-plane,master   8m18s   v1.23.7
```
