### ISSUE TITLE
Windows worker nodes support

### ISSUE THREAD

**Issue by vmasule** [kubernetes/kops#11829] opened 2021-06-21 11:48 UTC
Hi, Is it possible to provision Windows Worker nodes as instance group using kOPS? If there official support for this feature if not, is there any plan to add that or work in progress? We have a business use case where windows and linux node should co-exist in single K8s cluster. Pls provide insight on this.

**Comment by rifelpet** [comment] 2021-06-21 16:42
This is a duplicate of https://github.com/kubernetes/kops/issues/2422

At the moment I'm not aware of any updates on this, but PRs or assistance in adding Windows support will be welcome.

/close

**Closed** 2021-06-21 16:42 UTC
