### ISSUE TITLE
Allow tolerations in instance group config

### ISSUE THREAD

**Issue by pnegahdar** [kubernetes/kops#1497] opened 2017-01-16 20:13 UTC
It would be nice to have tolerations in the instance group config considering there already is node label: 

https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/instancegroup.go#L86

**Comment by chrislovecnm** [comment] 2017-01-16 20:18
More information please ;)  Also contributions are always welcome!

**Comment by pnegahdar** [comment] 2017-01-16 20:22
Re more information: 

https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md

Nodes in kubernetes can be tainted with special annotations like low-mem=true to disable scheduling unless the pod explicitly tolerates that taint. Other taints can include subnet/networking policies, etc. It would be nice to have nodes in an instance group auto-apply taints on creation if they are listed in the IG config. 


Re contributions: feel free to assign to me. Are we past the 1.5 cut already? wont be able to get to it till the end of the week

Aside: is there a tag for issues that are expected to be fixed before a given release (say 1.5)?

**Comment by ese** [comment] 2017-01-16 22:00
I think this is a duplicate of #803 
This will be trivial to implement once https://github.com/kubernetes/kubernetes/pull/31647 is released

**Comment by kris-nova** [comment] 2017-01-17 04:23
> Re contributions: feel free to assign to me. Are we past the 1.5 cut already? wont be able to get to it till the end of the week

**No. We are still in 1.5 alpha** (So you can still code this!)

Please shoot me a message on slack if you would like to go through the PR process, happy to help out anyway I can.

**Comment by robinpercy** [comment] 2017-02-03 13:46
@kris-nova @pnegahdar I'd like to take this on if it's still up for grabs.

**Comment by pnegahdar** [comment] 2017-02-07 15:39
@robinpercy please feel free to. Haven't gotten around to this yet.

**Comment by geojaz** [comment] 2017-10-23 06:24
closed in #1812 :)

**Closed by geojaz** 2017-10-23 06:24 UTC
