### ISSUE TITLE
I am unable to create the cluster as it fails to export the Kubecfg for cluster. Seems to a bug

### ISSUE THREAD

**Issue by tarnjeetsingh** [kubernetes/kops#10736] opened 2021-02-05 03:53 UTC
root@ip-172-31-15-52:/home/ubuntu# kops update cluster --name tarnjeetdemo.valaxy.net --yes --admin
I0205 03:51:09.326878    2589 dns.go:96] Private DNS: skipping DNS validation
I0205 03:51:09.611193    2589 executor.go:111] Tasks: 0 done / 79 total; 44 can run
I0205 03:51:10.492653    2589 executor.go:111] Tasks: 44 done / 79 total; 15 can run
I0205 03:51:11.684376    2589 executor.go:111] Tasks: 59 done / 79 total; 18 can run
I0205 03:51:11.949528    2589 executor.go:111] Tasks: 77 done / 79 total; 2 can run
I0205 03:51:12.065721    2589 executor.go:111] Tasks: 79 done / 79 total; 0 can run
I0205 03:51:12.065936    2589 dns.go:156] Pre-creating DNS records
I0205 03:51:12.672816    2589 update_cluster.go:313] Exporting kubecfg for cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c56de4]

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi/cloudup/awstasks.FindElasticLoadBalancerByNameTag(0x476a180, 0xc000e21800, 0xc0002a1b00, 0xc000e1c8a0, 0x17, 0xc000e1df80, 0x1b)
        upup/pkg/fi/cloudup/awstasks/dnsname.go:156 +0x84
k8s.io/kops/upup/pkg/fi/cloudup/awstasks.FindDNSName(0x476a180, 0xc000e21800, 0xc0002a1b00, 0x476a180, 0xc000e21800, 0x38501, 0xc00048d6c8)
        upup/pkg/fi/cloudup/awstasks/dnsname.go:135 +0x90
k8s.io/kops/pkg/commands.(*CloudDiscoveryStatusStore).GetApiIngressStatus(0x660ae18, 0xc0002a1b00, 0xa, 0xc000e1c900, 0x1b, 0xc00048d790, 0x1c)
        pkg/commands/status_discovery.go:56 +0x10e
k8s.io/kops/pkg/kubeconfig.BuildKubecfg(0xc0002a1b00, 0x46d3c80, 0xc000e1f7d0, 0x472d8e0, 0xc000e223a0, 0x469a980, 0x660ae18, 0x3aef6cfb4000, 0x0, 0x0, ...)
        pkg/kubeconfig/create_kubecfg.go:74 +0x258
main.RunUpdateCluster(0x46e69c0, 0xc0000540d0, 0xc000585400, 0x7ffc5fa187f4, 0x17, 0x4695560, 0xc00000e020, 0xc0003ec5a0, 0x5, 0x4131974, ...)
        cmd/kops/update_cluster.go:317 +0x17d8
main.NewCmdUpdateCluster.func1(0xc0002cc2c0, 0xc0000a3a80, 0x0, 0x4)
        cmd/kops/update_cluster.go:113 +0x109
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc0002cc2c0, 0xc0000a3a40, 0x4, 0x4, 0xc0002cc2c0, 0xc0000a3a40)
        vendor/github.com/spf13/cobra/command.go:846 +0x2c2
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x65bfe40, 0x660ae18, 0x0, 0x0)
        vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:887
main.Execute()
        cmd/kops/root.go:97 +0x8f
main.main()
        cmd/kops/main.go:24 +0x25

**Comment by bharath-123** [comment] 2021-02-05 10:49
This seems to be a duplicate of this issue https://github.com/kubernetes/kops/issues/10717 It has been fixed and will be available in the 1.19.1 release.

**Comment by tarnjeetsingh** [comment] 2021-02-05 10:51
by when can we expect next release

**Comment by Schachte** [comment] 2021-02-19 15:16
Seeing this issue as well when removing letter balancer and utilizing DNS instead

```
spec:
  api:
    dns: {}
```

works when load balancer type is used:
https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md

**Comment by Schachte** [comment] 2021-02-19 15:53
Seems to be fixed with alpha release I tried. However, using DNS in API spec instead of load balancer isn't working.

**Closed** 2021-07-19 17:22 UTC
Labels: lifecycle/rotten
