### ISSUE TITLE
Terraform Doesn't Work With Private Hosted Zones

### ISSUE THREAD

**Issue by jamesgoodhouse** [kubernetes/kops#1885] opened 2017-02-13 22:06 UTC
I am attempting to use kops a private topology cluster with a private dns, however I receive the message `Route53 private hosted zones are not supported for terraform`. It is unclear if this means I need to instead create Route53 entries manually prior to trying to export to TF using kops, or if kops is just unable to run this command at all.

**Comment by mboret** [comment] 2017-02-15 09:37
I've the same issue, with private or public Route53 zone, I'm receving the same error. `Route53 private hosted zones are not supported for terraform`.
I'm executing this command:
`kops create cluster --vpc vpc-dc26b8 k8s-test.internal --zones=eu-west-1a,eu-west-1b,eu-west-1c --dns private --node-count 2 --master-zones eu-west-1a --node-size t2.small --master-size t2.medium --out=. --target=terraform --state s3://s3.k8s.test`

**Comment by banchee** [comment] 2017-02-15 13:21
Im getting the same issue, kops 1.5.1 

`kops create cluster --name=dev.pdg.io --cloud=aws --target=terraform --out=. --state=s3://pdg-kube-aws --zones=eu-central-1a --dns-zone=dev.*****.io --node-size=t2.small --master-size=t2.small --dns=private`

**Comment by chrislovecnm** [comment] 2017-02-19 20:27
@justinsb any ideas?

**Comment by bregtcoenen** [comment] 2017-03-13 15:08
Any updates here? I am having the same issue

**Comment by jrnt30** [comment] 2017-03-21 13:48
I believe this is a duplicate of #1848. There is a concern around how to "manage" or "acquire" information about that private hosted zone with Terraform in a repeatable and safe way.

**Comment by bregtcoenen** [comment] 2017-03-23 14:45
I ended up setting up my VPC, subnets, route tables, DNS private zone, ... manually with terraform.
I tagged my route-tables, igw, and subnets with the following tag.
`KubernetesCluster = "${var.kops_cluster_name}"` 
Obviously, var.kops_cluster_name is the name of my cluster.

In my kops kops create cluster command I specified my VPC, network and private dns zone created by terraform. I didn't specify terraform output here.

After the creation, I've updated the cluster configuration so that the subnets match the ones I 've created. 

>    - cidr: 10.200.32.0/19
>     id: subnet-e43xxxxx
>     name: eu-central-1a
>     type: Private
>     zone: eu-central-1a

After that I applied the changes.


At this point I can manage my kubernetes resources with kops and my other resources with terraform. 


I found most of the required info to get here in this post https://github.com/kubernetes/kops/blob/master/docs/run_in_existing_vpc.md

**Comment by jrnt30** [comment] 2017-04-07 11:25
I believe this has been addressed in https://github.com/kubernetes/kops/pull/2297

**Comment by j0sh3rs** [comment] 2017-06-14 00:58
This issue is still happening in 1.6.1

**Comment by moleksyuk** [comment] 2017-10-25 12:48
Still reproducible in 1.7.1 as well.

**Comment by hristovpln** [comment] 2017-11-02 14:50
Just tried with:
--dns private
.. and it worked
kops v1.7.0

**Comment by chrislovecnm** [comment] 2017-11-02 18:34
Closing, please use 1.7.1 kops, as it has a cve patch in it

**Closed by chrislovecnm** 2017-11-02 18:34 UTC

**Comment by timurkhafizov** [comment] 2017-12-08 10:09
Running the simple 
`kops create cluster --name=sample.domain.com --zones=eu-west-1a --target=terraform --out=./kops/sample --dns=private --dns-zone=domain.com`
fails with output:
```
...
I1208 11:05:58.879563   28104 dnszone.go:242] Check for existing route53 zone to re-use with name "domain.com"
W1208 11:05:59.001850   28104 executor.go:109] error running task "DNSZone/domain.com" (9m57s remaining to succeed): Creation of Route53 hosted zones is not supported for terraform
I1208 11:05:59.001887   28104 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)
...
```

I am using kops 1.8.0.
Has it been fixed in 1.8.0 as well?

**Comment by admssa** [comment] 2018-02-25 13:08
kops 1.8.1 the same. 
terraform export isn't working for private topology

```
kops create cluster \
              --state=s3://bucket\
              --name=k8s.domain.local \
              --dns=private \
              --dns-zone=domain.local \
              --master-size=t2.medium \
              --node-size=t2.medium \
              --zones=eu-west-1a \
              --master-zones=eu-west-1a \
              --node-count=3 \
              --master-count=1 \
              --image=ami-a61464df \
              --master-volume-size=50 \
              --node-volume-size=50 \
              --topology=private \
              --networking=calico \
	      --ssh-public-key=~/.ssh/development-kubernetes.pub \
	      --api-loadbalancer-type=internal \
              --kubernetes-version=1.9.3 \
              --network-cidr=10.253.0.0/16 \
              --out=../../../../../terraform/k8s \
              --target=terraform```

```
I0225 19:41:15.567792   30890 dnszone.go:242] Check for existing route53 zone to re-use with name "domain.local"
W0225 19:41:17.100616   30890 executor.go:109] error running task "DNSZone/domain.local" (9m14s remaining to succeed): Creation of Route53 hosted zones is not supported for terraform
I0225 19:41:17.100707   30890 executor.go:124] No progress made, sleeping before retrying 1 failed task(s)
```

**Comment by cobravsninja** [comment] 2018-06-05 19:16
Had the same issue before payed attention to the following statement:

> The only requirement to trigger this is to have the cluster name end with .k8s.local
