### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x394490d]

### ISSUE THREAD

**Issue by BlackCheshire** [kubernetes/kops#12576] opened 2021-10-21 19:18 UTC
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.22.0 (git-8ba0d78c0be251c7dd5584d178c3e342037705df)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.21.5

**3. What cloud provider are you using?**
AWS 

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops edit ig nodes --state=s3://my-state
edit max and min size nodes
save and exit

**5. What happened after the commands executed?**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x394490d]

goroutine 1 [running]:
k8s.io/kops/upup/pkg/fi/cloudup.PopulateInstanceGroupSpec(0xc00052e500, 0xc000321500, 0x7f621ba5e9a0, 0xc0003eafc0, 0xc000102d80, 0x0, 0x0, 0x0)
	upup/pkg/fi/cloudup/populate_instancegroup_spec.go:164 +0x2ed
main.updateInstanceGroup(0x5572650, 0xc0001a4008, 0x55d4308, 0xc00053b220, 0xc000102d80, 0xc00052e500, 0xc0007e8000, 0xc000321500, 0x0, 0xc0009d14a0, ...)
	cmd/kops/edit_instancegroup.go:291 +0xab
main.RunEditInstanceGroup(0x5572650, 0xc0001a4008, 0xc000380138, 0x551c7e0, 0xc0001aa008, 0xc00014cc30, 0x0, 0x0)
	cmd/kops/edit_instancegroup.go:268 +0xfe8
main.NewCmdEditInstanceGroup.func2(0xc000538000, 0xc0008cf080, 0x1, 0x2, 0x0, 0x0)
	cmd/kops/edit_instancegroup.go:107 +0x5d
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).execute(0xc000538000, 0xc0008cf060, 0x2, 0x2, 0xc000538000, 0xc0008cf060)
	vendor/github.com/spf13/cobra/command.go:856 +0x472
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x78169e0, 0x7866630, 0x0, 0x0)
	vendor/github.com/spf13/cobra/command.go:974 +0x375
k8s.io/kops/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	vendor/github.com/spf13/cobra/command.go:902
main.Execute()
	cmd/kops/root.go:95 +0x8f
main.main()
	cmd/kops/main.go:20 +0x25

**Comment by rifelpet** [comment] 2021-10-22 00:05
Duplicate of #12557 and will be fixed in 1.22.1

/close

**Closed** 2021-10-22 00:05 UTC
Labels: kind/bug
