### ISSUE TITLE
ASG warm pool supports terraform target

### ISSUE THREAD

**Issue by choutone** [kubernetes/kops#12052] opened 2021-07-27 12:43 UTC
/kind feature

**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Setup `warmPool` feature on Kops `1.21` with a terraform target actually does not work and return:
```
 ASG warm pool is not supported by the terraform target
```

It could be nice to be able to use this feature with `terraform` and `cloudformation` target. :slightly_smiling_face: 

**2. Feel free to provide a design supporting your feature request.**

**Comment by johngmyers** [comment] 2021-07-27 17:59
Duplicate of #11633
/close

**Closed** 2021-07-27 17:59 UTC
Labels: kind/feature
