### ISSUE TITLE
Cannot identify spot and on-demand EC2 instances when using mixedInstancePolicy in ASG

### ISSUE THREAD

**Issue by rajakshay** [kubernetes/kops#9007] opened 2020-04-27 23:45 UTC
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
* It would be useful to identify whether an EC2 instance is spot or on-demand in a mixedInstancePolicy ASG. 
* Ability to add this info as`cloudLabel` or `NodeLabel`.

This would help with:
1. Targeting workloads to spot Instances.
2. Be able to filter spot instances based on k8s node labels.

**2. Feel free to provide a design supporting your feature request.**
This info is not directly available in EC2 Metadata. Getting this info is 2 folds:
1. Get the instance id for the EC2 instance. Then,
2. Query whether or not it is spot: https://gist.github.com/urjitbhatia/c5af8a3d53661cb3d4e896feae23fc1d

Hopefully, this can be made available out-of-the-box for kops users.

**Comment by coderanger** [comment] 2020-04-28 02:17
Duplicate of #8923

**Closed** 2020-04-28 05:27 UTC
