### ISSUE TITLE
Protokube can't be pulled from dockerhub

### ISSUE THREAD

**Issue by jacohend** [kubernetes/kops#2785] opened 2017-06-21 00:24 UTC
Using kops 1.6.1 to deploy an aws cluster. On one of the nodes' syslogs, from the nodeup task:
```
Jun 21 00:21:24 ip-172-20-56-180 docker[30617]: Unable to find image 'protokube:1.6.1' locally
Jun 21 00:21:24 ip-172-20-56-180 dockerd[30053]: time="2017-06-21T00:21:24.009850050Z" level=error msg="Handler for POST /v1.24/containers/create returned error: No such image: protokube:1.6.1"
Jun 21 00:21:24 ip-172-20-56-180 auditd[858]: Audit daemon rotating log files with keep option
Jun 21 00:21:24 ip-172-20-56-180 dockerd[30053]: time="2017-06-21T00:21:24.845518122Z" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
Jun 21 00:21:24 ip-172-20-56-180 docker[30617]: Pulling repository docker.io/library/protokube
Jun 21 00:21:25 ip-172-20-56-180 dockerd[30053]: time="2017-06-21T00:21:25.134478544Z" level=error msg="Not continuing with pull after error: Error: image library/protokube:1.6.1 not found"
Jun 21 00:21:25 ip-172-20-56-180 docker[30617]: /usr/bin/docker: Error: image library/protokube:1.6.1 not found.
```
Did it always use the same hardcoded version string (1.6.1) erroneously everywhere to pull down all assets?

**Comment by chrislovecnm** [comment] 2017-06-21 21:02
Protokube container is actually d/l from s3 and loaded. These messages are typically a non issue, and are caused by the system being eventually consistent.

Is the cluster not creating?

**Comment by dng-dev** [comment] 2017-09-08 13:55
Hey @chrislovecnm i also run into this issue. 

`Sep  8 13:47:44 ip-172-19-23-111 dockerd[1451]: time="2017-09-08T13:47:44.737429211Z" level=error msg="Handler for POST /v1.24/containers/create returned error: No such image: protokube:1.7.0"
Sep  8 13:47:44 ip-172-19-23-111 docker[1864]: Unable to find image 'protokube:1.7.0' locally
Sep  8 13:47:45 ip-172-19-23-111 dockerd[1451]: time="2017-09-08T13:47:45.829372166Z" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
Sep  8 13:47:45 ip-172-19-23-111 docker[1864]: Pulling repository docker.io/library/protokube
Sep  8 13:47:46 ip-172-19-23-111 dockerd[1451]: time="2017-09-08T13:47:46.199303827Z" level=error msg="Not continuing with pull after error: Error: image library/protokube:1.7.0 not found"
Sep  8 13:47:46 ip-172-19-23-111 docker[1864]: /usr/bin/docker: Error: image library/protokube:1.7.0 not found.
Sep  8 13:47:46 ip-172-19-23-111 docker[1864]: See '/usr/bin/docker run --help'.
Sep  8 13:47:46 ip-172-19-23-111 systemd[1]: protokube.service: main process exited, code=exited, status=125/n/a
Sep  8 13:47:46 ip-172-19-23-111 systemd[1]: Unit protokube.service entered failed state.
Sep  8 13:47:48 ip-172-19-23-111 systemd[1]: protokube.service holdoff time over, scheduling restart.
Sep  8 13:47:48 ip-172-19-23-111 systemd[1]: Stopping Kubernetes Protokube Service...
Sep  8 13:47:48 ip-172-19-23-111 systemd[1]: Starting Kubernetes Protokube Service...
Sep  8 13:47:48 ip-172-19-23-111 systemd[1]: Started Kubernetes Protokube Service.
Sep  8 13:47:48 ip-172-19-23-111 dockerd[1451]: time="2017-09-08T13:47:48.237078937Z" level=error msg="Handler for POST /v1.24/containers/create returned error: No such image: protokube:1.7.0"
Sep  8 13:47:48 ip-172-19-23-111 docker[1874]: Unable to find image 'protokube:1.7.0' locally
Sep  8 13:47:49 ip-172-19-23-111 dockerd[1451]: time="2017-09-08T13:47:49.332156278Z" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
Sep  8 13:47:49 ip-172-19-23-111 docker[1874]: Pulling repository docker.io/library/protokube
Sep  8 13:47:49 ip-172-19-23-111 dockerd[1451]: time="2017-09-08T13:47:49.709454374Z" level=error msg="Not continuing with pull after error: Error: image library/protokube:1.7.0 not found"`

when i ssh into this box and manually execute following commands i got it up and running.
`
/usr/bin/docker pull chrislovecnm/protokube:1.7.0
/usr/bin/docker tag chrislovecnm/protokube:1.7.0 library/protokube:1.7.0
`
download the file "https://kubeupv2.s3.amazonaws.com/kops/1.7.0/images/protokube.tar.gz" via curl and wget was working from the instance itself. I am Using kops 1.7.0

**Comment by chrislovecnm** [comment] 2017-10-14 05:00
Protokube is d/l from s3 and does not exist in a registry. It is imported into docker once uncompressed. Any questions?

**Comment by chrislovecnm** [comment] 2017-11-05 06:09
Closing as answered

**Closed by chrislovecnm** 2017-11-05 06:09 UTC

**Comment by mausch** [comment] 2018-02-15 16:44
I'm using kops 1.8.1 and seeing this same error. Even if it is harmless (is it?), any such "invalid" errors tend to swamp the logs and make it much harder to find the cause of actual issues.

**Comment by Artiax** [comment] 2018-02-16 14:38
This is a genuine issue that occurs on our master (only) nodes. For some reason when protokube service is started it's not able to find the docker image and keeps looping indefinetely - the only way to break the loop is to re-run the docker load command manually. Version 1.8.0 kops (1.8.4 k8s).

**Comment by Globegitter** [comment] 2018-04-03 14:45
@Artiax I am using the latest CoreOS AMI `595879546273/CoreOS-stable-1688.4.0-hvm` and seeing the same isse with kops 1.9.0-beta.1 - how does one set docker to use overlay2?

**Comment by andrewsykim** [comment] 2018-04-03 16:13
Seems like a race between when docker is restarted with overlay2 and when nodeup pulls the image. I think the right solution here may be to issue a restart on `kops-configuration.service` if docker is ever restarted. Thoughts?

**Comment by andrewsykim** [comment] 2018-04-03 16:53
I think https://github.com/kubernetes/kops/pull/4894 will work
